---
- name: Add dropbox signing key
  when: mtype == 'personal'
  gpg_key:
    fpr: 1C61A2656FB57B7E4DE0F4C1FC918B335044912E

- name: Install sync apps
  when: mtype == 'personal'
  kewlfft.aur.aur:
    name:
      - dropbox

- name: Add 1password signing key
  when: mtype != 'media' and mtype != 'server'
  gpg_key:
    fpr: 3FEF9748469ADBE15DA7CA80AC2D62742012EA22

- name: Install password apps
  when: mtype != 'media' and mtype != 'server'
  kewlfft.aur.aur:
    name:
      - 1password
      - 1password-cli

- name: Install keepass
  when: mtype != 'server'
  become: true
  community.general.pacman:
    name: keepass

- name: Install yubikey tools
  when: mtype == 'personal'
  become: true
  community.general.pacman:
    name:
      - ccid
      - hopenpgp-tools
      - pcsclite
      - yubikey-manager
      - yubikey-personalization
      - yubikey-personalization-gui

- name: Install libreoffice
  when: mtype != 'media' and mtype != 'server'
  become: true
  community.general.pacman:
    name:
      - hunspell
      - hunspell-en_au
      - hunspell-en_ca
      - hunspell-en_gb
      - hunspell-en_us
      - hunspell-es_any
      - hunspell-es_es
      - hunspell-es_mx
      - hunspell-fr
      - hunspell-it
      - hyphen
      - hyphen-en
      - hyphen-es
      - hyphen-fr
      - hyphen-it
      - libreoffice-fresh
      - libreoffice-fresh-en-gb
      - libreoffice-fresh-es
      - libreoffice-fresh-fr
      - libreoffice-fresh-it
      - mythes
      - mythes-en
      - mythes-es
      - mythes-fr
      - mythes-it

- name: Install the gimp
  when: mtype != 'media' and mtype != 'server'
  become: true
  community.general.pacman:
    name:
      - gimp
      - gimp-extras
      - xsane-gimp

- name: Install graphics extras
  when: mtype == 'personal'
  become: true
  community.general.pacman:
    name:
      - dcraw
      - inkscape

- name: Install chat programs
  when: mtype != 'media' and mtype != 'server'
  become: true
  community.general.pacman:
    name:
      - aspell
      - aspell-en
      - aspell-es
      - aspell-fr
      - aspell-it
      - hexchat
      - pidgin
      - pidgin-otr
      - purple-plugin-pack

- name: Install thunderbird
  when: mtype == 'personal'
  become: true
  community.general.pacman:
    name:
      - thunderbird
      - thunderbird-i18n-en-us
      - thunderbird-i18n-es-es
      - thunderbird-i18n-fr
      - thunderbird-i18n-it

- name: Install gnucash
  when: mtype == 'personal'
  become: true
  community.general.pacman:
    name:
      - gnucash
      - gnucash-docs
      - perl-date-manip
      - perl-finance-quote
      - perl-libwww
      - perl-lwp-protocol-https

- name: Install raspberry pi imager
  when: mtype == 'personal'
  become: true
  community.general.pacman:
    name: rpi-imager
