---
- name: Adding Dropbox signing key
  when: mtype == 'personal'
  gpg_key:
    fpr: 1C61A2656FB57B7E4DE0F4C1FC918B335044912E

- name: Installing Dropbox
  when: mtype == 'personal'
  kewlfft.aur.aur:
    name: dropbox
    state: present

- name: Adding 1Password signing key
  when: mtype != 'media'
  gpg_key:
    fpr: 3FEF9748469ADBE15DA7CA80AC2D62742012EA22

- name: Installing 1Password
  when: mtype != 'media'
  kewlfft.aur.aur:
    name:
      - 1password
      - 1password-cli
    state: present

- name: Installing KeePassXC
  become: true
  community.general.pacman:
    name: keepassxc
    state: present

- name: Installing YubiKey tools
  when: mtype == 'personal'
  become: true
  community.general.pacman:
    name:
      - ccid
      - hopenpgp-tools
      - pcsclite
      - yubikey-manager
      - yubikey-personalization
      - yubikey-personalization-gui
    state: present

- name: Installing LibreOffice
  when: mtype != 'media'
  become: true
  community.general.pacman:
    name:
      - hunspell
      - hunspell-en_au
      - hunspell-en_ca
      - hunspell-en_gb
      - hunspell-en_us
      - hunspell-es_any
      - hunspell-es_es
      - hunspell-es_mx
      - hunspell-fr
      - hunspell-it
      - hyphen
      - hyphen-en
      - hyphen-es
      - hyphen-fr
      - hyphen-it
      - libreoffice-fresh
      - libreoffice-fresh-en-gb
      - libreoffice-fresh-es
      - libreoffice-fresh-fr
      - libreoffice-fresh-it
      - mythes
      - mythes-en
      - mythes-es
      - mythes-fr
      - mythes-it
    state: present

- name: Installing Scribus
  when: mtype != 'media'
  become: true
  community.general.pacman:
    name: scribus
    state: present

- name: Installing the GIMP
  when: mtype != 'media'
  become: true
  community.general.pacman:
    name:
      - gimp
      - gimp-extras
      - xsane-gimp
    state: present

- name: Installing photography tools
  when: mtype != 'media'
  become: true
  community.general.pacman:
    name:
      - darktable
      - dcraw
      - dnglab
      - rawtherapee

- name: Installing Thunderbird
  when: mtype == 'personal'
  become: true
  community.general.pacman:
    name:
      - thunderbird
      - thunderbird-i18n-en-us
      - thunderbird-i18n-es-es
      - thunderbird-i18n-fr
      - thunderbird-i18n-it
    state: present

- name: Installing GnuCash
  when: mtype == 'personal'
  become: true
  community.general.pacman:
    name:
      - gnucash
      - gnucash-docs
      - perl-date-manip
      - perl-finance-quote
      - perl-libwww
      - perl-lwp-protocol-https
    state: present

- name: Installing RaspberryPi Imager
  when: mtype == 'personal'
  become: true
  community.general.pacman:
    name: rpi-imager
    state: present
