---
- name: Install zsh
  become: true
  community.general.pacman:
    name:
      - zsh
      - grml-zsh-config
      - zsh-autosuggestions
      - zsh-syntax-highlighting
      - zsh-completions
      - zsh-theme-powerlevel10k

- name: Install gitstatus
  become: true
  community.general.pacman:
    name: gitstatus

- name: Install terminal fonts
  when: mtype != 'server'
  become: true
  community.general.pacman:
    name:
      - ttf-meslo-nerd-font-powerlevel10k
      - ttf-jetbrains-mono-nerd
      # - ttf-jetbrains-mono
      # - ttf-nerd-fonts-symbols-mono

- name: Install main cli apps
  become: true
  community.general.pacman:
    name:
      - tmux
      - htop
      - pwgen
      - ctags
      - ripgrep
      - the_silver_searcher
      - bat
      - fd
      - fzf
      - go-yq
      - neofetch
      - thefuck
      - tldr
      - bind
      - net-tools
      - p7zip
      - whois
      - jq
      - vivid
      - zoxide

- name: Install secondary cli apps
  when: mtype != 'media'
  become: true
  community.general.pacman:
    name:
      - moreutils
      - ncdu
      - bat-extras
      - difftastic
      - dos2unix
      - github-cli
      - glab
      - nmap
      - pv
      - urlwatch

- name: Install shared secondary cli apps
  when: mtype == 'personal' or mtype == 'media'
  become: true
  community.general.pacman:
    name:
      - cdrtools
      - unrar

- name: Install backup apps
  become: true
  community.general.pacman:
    name:
      - borg
      - rclone
      - pass
      - pass-otp

- name: Add archuseriso signing key
  when: mtype != 'media' and mtype != 'server'
  gpg_key:
    fpr: A5143BB56952B3189F49A175FAC4560863BEEC34

- name: Install archuseriso from aur
  when: mtype != 'media' and mtype != 'server'
  kewlfft.aur.aur:
    name: archuseriso

- name: Install tailscale
  when: mtype == 'personal' or mtype == 'media'
  become: true
  community.general.pacman:
    name: tailscale
