---
- name: Installing zsh
  become: true
  community.general.pacman:
    name:
      - grml-zsh-config
      - zsh
      - zsh-autosuggestions
      - zsh-completions
      - zsh-syntax-highlighting
      - zsh-theme-powerlevel10k
    state: present

- name: Installing gitstatus
  become: true
  community.general.pacman:
    name: gitstatus
    state: present

- name: Installing terminal fonts
  become: true
  community.general.pacman:
    name:
      - ttf-jetbrains-mono-nerd
      - ttf-meslo-nerd-font-powerlevel10k
      # - ttf-jetbrains-mono
      # - ttf-nerd-fonts-symbols-mono
    state: present

- name: Installing main CLI programs
  become: true
  community.general.pacman:
    name:
      - 7zip
      - bat
      - bind
      - bpftop
      - broot
      - ctags
      - fastfetch
      - fd
      - fzf
      - htop
      - jq
      - lsd
      - net-tools
      - nnn
      - nvtop
      - pwgen
      - ripgrep
      - screen
      - the_silver_searcher
      - thefuck
      - tldr
      - tmux
      - vivid
      - whois
      - zoxide
    state: present

- name: Installing secondary CLI programs
  when: mtype != 'media'
  become: true
  community.general.pacman:
    name:
      - bat-extras
      - cloc
      - difftastic
      - dos2unix
      - lstr
      - fq
      - github-cli
      - glab
      - glim
      - miller
      - moreutils
      - ncdu
      - nmap
      - pv
      - sd
      - urlwatch
    state: present

- name: Installing shared secondary CLI programs
  when: mtype == 'personal' or mtype == 'media'
  become: true
  community.general.pacman:
    name:
      - cdrtools
      - magic-wormhole
      - nvme-cli
      - potrace
      - unrar
    state: present

- name: Installing backup programs
  become: true
  community.general.pacman:
    name:
      - age
      - borg
      - pass
      - pass-otp
      - rclone
    state: present

- name: Installing Tailscale
  when: mtype == 'personal' or mtype == 'media'
  become: true
  community.general.pacman:
    name: tailscale
    state: present

- name: Installing irssi
  when: mtype != 'media'
  become: true
  community.general.pacman:
    name: irssi
    state: present

- name: Installing atuin
  become: true
  community.general.pacman:
    name: atuin
    state: present
