---
- name: install zsh
  become: true
  pacman:
    name:
      - zsh
      - grml-zsh-config
      - zsh-autosuggestions
      - zsh-syntax-highlighting
      - zsh-completions
      - zsh-theme-powerlevel10k

- name: install terminal fonts
  when: mtype != 'server'
  aur:
    name:
      - ttf-meslo-nerd-font-powerlevel10k
      - nerd-fonts-jetbrains-mono
      # - ttf-jetbrains-mono
      # - ttf-nerd-fonts-symbols-mono

- name: install main cli apps
  become: true
  pacman:
    name:
      - tmux
      - htop
      - pwgen
      - ctags
      - ripgrep
      - the_silver_searcher
      - bat
      - fd
      - fzf
      - thefuck
      - tldr
      - bind
      - net-tools
      - nmap
      - whois
      - jq
      - vivid
      - zoxide

- name: install main cli apps from aur
  aur:
    name:
      - go-yq

- name: install secondary cli apps
  when: "mtype == 'personal'"
  become: true
  pacman:
    name:
      - moreutils
      - dos2unix
