---
- name: install zsh
  become: true
  pacman:
    name:
      - zsh
      - grml-zsh-config
      - zsh-autosuggestions
      - zsh-syntax-highlighting
      - zsh-completions
      - zsh-theme-powerlevel10k

- name: install gitstatus
  become: true
  pacman: name=gitstatus

- name: install terminal fonts
  when: mtype != 'server'
  become: true
  pacman:
    name:
      - ttf-meslo-nerd-font-powerlevel10k
      - nerd-fonts-jetbrains-mono
      # - ttf-jetbrains-mono
      # - ttf-nerd-fonts-symbols-mono

- name: install main cli apps
  become: true
  pacman:
    name:
      - tmux
      - htop
      - pwgen
      - ctags
      - ripgrep
      - the_silver_searcher
      - bat
      - fd
      - fzf
      - go-yq
      - neofetch
      - thefuck
      - tldr
      - bind
      - net-tools
      - p7zip
      - whois
      - jq
      - vivid
      - zoxide

- name: install secondary cli apps
  when: mtype != 'media'
  become: true
  pacman:
    name:
      - moreutils
      - ncdu
      - bat-extras
      - difftastic
      - dos2unix
      - github-cli
      - glab
      - nmap
      - pv
      - urlwatch

- name: install shared secondary cli apps
  when: mtype == 'personal' or mtype == 'media'
  become: true
  pacman:
    name:
      - cdrtools
      - unrar

- name: install backup apps
  become: true
  pacman:
    name:
      - borg
      - rclone
      - pass
      - pass-otp

- name: add archuseriso signing key
  when: mtype != 'media' and mtype != 'server'
  gpg_key:
    fpr: A5143BB56952B3189F49A175FAC4560863BEEC34

- name: install archuseriso from aur
  when: mtype != 'media' and mtype != 'server'
  kewlfft.aur.aur: name=archuseriso

- name: install tailscale
  when: mtype == 'personal' or mtype == 'media'
  become: true
  pacman: name=tailscale
