---
- name: install ansible-extras
  become: true
  pacman:
    name:
      - ansible-lint
      - python-passlib
      - sshpass
      - yapf

- name: install keymapper
  become: true
  pacman: name=keymapper

- name: enable keymapperd
  become: true
  systemd: name=keymapperd.service enabled=yes

- name: start keymapperd
  become: true
  systemd: name=keymapperd.service state=started

- name: install terminal emulators
  become: true
  pacman:
    name:
      - xterm

- name: install cursors
  aur: name=xcursor-openzone

- name: install fonts
  become: true
  pacman:
    name:
      - ttf-liberation
      - ttf-bitstream-vera
      - gnu-free-fonts
      - ttf-carlito
      # - ttf-caladea
      - ttf-dejavu
      - libertinus-font
      - otf-fira-sans
      - otf-fira-mono
      - noto-fonts
      - noto-fonts-emoji
      - noto-fonts-extra
      - ttf-ubuntu-font-family
      - ttf-linux-libertine

- name: install fonts part two
  aur:
    name:
      - ttf-symbola
      - ttf-google-fonts-git

- name: install xfce themes
  become: true
  pacman:
    name:
      - xfce-theme-manager
      - elementary-icon-theme

- name: install xfce themes
  aur:
    name:
      - xfce-theme-greybird
      - shimmer-wallpapers
      - elementary-xfce-icons
      - paper-icon-theme-git
      - papirus-icon-theme-git
      - matcha-gtk-theme-git

- name: install bluetooth packages
  become: true
  pacman:
    name:
      - bluez
      - bluez-utils
      - blueman
      - pulseaudio-bluetooth

- name: enable bluetooth
  become: true
  systemd: name=bluetooth.service enabled=yes

- name: install redshift
  become: true
  pacman:
    name:
      - redshift
      - python-gobject
      - python-xdg

- name: ensure bluetooth download directory is correct
  gsetting:
    key: org.blueman.transfer.shared-path
    value: "'{{ ansible_user_dir }}/Downloads'"

- include: apps.yml
- include: cli.yml
