---
- name: Install ansible-extras
  become: true
  community.general.pacman:
    name:
      - ansible-lint
      - python-passlib
      - sshpass
      - yapf

- name: Install downgrade
  kewlfft.aur.aur:
    name: downgrade

- name: Install desktop apps
  ansible.builtin.include_tasks: apps.yml

- name: Install CLI programs
  ansible.builtin.include_tasks: cli.yml
