---
- name: Installing ansible tools
  become: true
  community.general.pacman:
    name:
      - ansible-lint
      - python-passlib
      - sshpass
      - yapf
    state: present

- name: Installing downgrade
  kewlfft.aur.aur:
    name: downgrade
    state: present

- name: Installing desktop applications
  ansible.builtin.include_tasks: apps.yml

- name: Installing CLI programs
  ansible.builtin.include_tasks: cli.yml
