---
- name: Installing finellictl dependencies
  become: true
  community.general.pacman:
    name:
      - go-yq
    state: present

- name: Installing finellictl
  become: true
  ansible.builtin.copy:
    dest: /usr/bin/finellictl
    group: root
    mode: "0755"
    owner: root
    src: finellictl

- name: Creating finelli configuration directory
  become: true
  ansible.builtin.file:
    group: root
    mode: "0755"
    owner: root
    path: /etc/finelli
    state: directory

- name: Copying finellictl configuration
  become: true
  ansible.builtin.template:
    dest: /etc/finelli/arch-install.yml
    group: root
    mode: "0644"
    owner: root
    src: arch-install.yml.j2
