---
- name: use systemd for ntp
  become: true
  command: timedatectl set-ntp true

- name: set timezone
  become: true
  community.general.timezone: name={{ timezone }}

- name: ensure baseline archlinux system
  become: true
  pacman:
    name:
      - base
      - base-devel
      - linux
      - linux-firmware
      - sof-firmware
      - posix

- name: install locale.gen
  become: true
  copy:
    dest: /etc/locale.gen
    owner: root
    group: root
    mode: 0644
    src: locale.gen
  register: locales_list

- name: locale-gen
  when: locales_list.changed
  become: true
  command: locale-gen

- name: install locale.conf
  become: true
  template:
    dest: /etc/locale.conf
    owner: root
    group: root
    mode: 0644
    src: locale.conf.j2

- name: install bootstrap packages
  become: true
  when: mtype != 'server'
  pacman:
    name:
      - grub
      - efibootmgr
      - btrfs-progs
      - dosfstools
      - ntfs-3g
      - e2fsprogs
      - exfat-utils
      - f2fs-tools
      - os-prober
      - lvm2
      - cryptsetup
      - mdadm
      - usbutils

- name: install video and input drivers
  become: true
  when: mtype != 'server'
  pacman:
    name:
      - xf86-video-vesa
      - xf86-input-libinput

- name: install intel video drivers
  become: true
  when: mtype != 'server' and gcard == 'intel'
  pacman:
    name:
      - xf86-video-intel

- name: install amd video drivers
  become: true
  when: mtype != 'server' and gcard == 'amd'
  pacman:
    name:
      - xf86-video-ati
      - xf86-video-amdgpu

- name: install intel microcode
  become: true
  when: mtype != 'server' and ansible_local.cpuinfo.cpu_vendor == 'Intel'
  pacman: name=intel-ucode

- name: install amd microcode
  become: true
  when: mtype != 'server' and ansible_local.cpuinfo.cpu_vendor == 'AMD'
  pacman: name=amd-ucode

- name: install mkinitcpio configuration
  become: true
  when: mtype != 'server'
  copy:
    dest: /etc/mkinitcpio.conf
    owner: root
    group: root
    mode: 0644
    src: mkinitcpio.conf
  register: mkinitcpio_config

- name: mkinitcpio
  when: mkinitcpio_config.changed
  become: true
  command: mkinitcpio -p linux

- name: ensure sudoer rule
  become: true
  copy:
    dest: /etc/sudoers.d/gsudo
    owner: root
    group: root
    mode: 0440
    src: sudoer
    validate: 'visudo -cf %s'

- include: pacman.yml

- name: install ansible-aur (from supermario repo)
  become: true
  pacman:
    name:
      - ansible-aur
      - ansible-gpg-key-git

- name: install pikaur
  aur: name=pikaur

- name: install networking tools
  become: true
  when: mtype != 'server'
  pacman:
    name:
      - iw
      - iwd
      - dialog
      - wpa_supplicant
      - easy-rsa
      - networkmanager
      - networkmanager-openvpn
      - crda
      - netctl

- name: install inetutils for `hostname`
  become: true
  pacman: name=inetutils

- name: install wireless regdom
  become: true
  when: mtype != 'server'
  template:
    dest: /etc/conf.d/wireless-regdom
    owner: root
    group: root
    mode: 0644
    src: wireless-regdom.j2

- name: install old base group packages
  become: true
  pacman:
    name:
      - logrotate
      - man-db
      - nano
      - perl
      - s-nail
      - texinfo
      - vi
      - man-pages
      - bash-completion

- name: install everywhere packages
  become: true
  pacman:
    name:
      - vim
      - vim-spell-en
      - vim-spell-es
      - vim-spell-fr
      - vim-spell-it
      - lynx
      - rsync
      - wget

- include: finellictl.yml
