---
- name: ensure baseline archlinux system
  become: true
  pacman:
    name:
      - base
      - base-devel
      - linux
      - linux-firmware
      - posix

- name: install bootstrap packages
  become: true
  pacman:
    name:
      - grub
      - efibootmgr
      - btrfs-progs
      - dosfstools
      - ntfs-3g
      - e2fsprogs
      - exfat-utils
      - os-prober
      - lvm2
      - cryptsetup
      - mdadm
      - usbutils

- name: install video and input drivers
  become: true
  pacman:
    name:
      - xf86-video-vesa
      - xf86-input-libinput

- name: install intel video drivers
  become: true
  when: gcard == 'intel'
  pacman:
    name:
      - xf86-video-intel

- name: install amd video drivers
  become: true
  when: gcard == 'amd'
  pacman:
    name:
      - xf86-video-ati
      - xf86-video-amdgpu

- name: install intel microcode
  become: true
  when: ansible_processor[1] == 'GenuineIntel'
  pacman: name=intel-ucode


- include: pacman.yml

- name: install ansible-aur (from supermario repo)
  pacman:
    name:
      - ansible-aur
      - ansible-gpg-key-git
      - ansible-gsetting-git

- name: install pikaur
  aur: name=pikaur

- name: install networking tools
  become: true
  pacman:
    name:
      - iw
      - iwd
      - dialog
      - wpa_supplicant
      - easy-rsa
      - networkmanager
      - networkmanager-openvpn
      - crda
      - inetutils
      - netctl

- name: install old base group packages
  become: true
  pacman:
    name:
      - logrotate
      - man-db
      - nano
      - perl
      - s-nail
      - texinfo
      - vi
      - man-pages
      - bash-completion
