---
# all of the information we need is available in ansible_devices fact, but
# there are nasty nested lists and dictionaries to pull the information out
# with a nasty json_query, and just asking the blkid with the disk
# by-partlabel is much simpler and easier to understand
- name: Getting root volume disk UUID
  become: true
  ansible.builtin.command: >-
    blkid -s UUID -o value /dev/disk/by-partlabel/CRYPTROOT
  register: cryptroot_blkid
  changed_when: false
  failed_when: cryptroot_blkid.rc != 0

- name: Setting CRYPTROOT UUID as fact
  ansible.builtin.set_fact:
    cryptroot_uuid: "{{ cryptroot_blkid.stdout }}"

- name: Detecting installed kernel package
  ansible.builtin.shell: >-
    set -e -o pipefail;
    basename "$(find /usr/lib/modules/* -prune -print | head -n 1)"
  register: installed_kernel_shell
  changed_when: false
  failed_when: installed_kernel_shell.rc != 0

- name: Setting installed kernel package as fact
  ansible.builtin.set_fact:
    installed_kernel: "{{ installed_kernel_shell.stdout }}"

- name: Installing finellictl
  ansible.builtin.include_tasks: finellictl.yml

- name: Configuring systemd services
  ansible.builtin.include_tasks: systemd.yml

- name: Setting system timezone
  become: true
  when: mmode != 'setup'
  community.general.timezone:
    name: "{{ timezone }}"

- name: Installing baseline Archlinux system
  become: true
  community.general.pacman:
    name:
      - base
      - base-devel
      - dracut
      - dracut-hook-uefi
      - linux
      - linux-firmware
      - posix
      - sof-firmware
    state: present

# iptables is a dependency of systemd (part of base)
- name: Replacing "iptables" with "iptables-nft"
  become: true
  community.general.pacman:
    name: iptables-nft
    state: present

- name: Installing tpm tools
  become: true
  when: hastpm == 'true'
  community.general.pacman:
    name: tpm2-tools
    state: present

- name: Installing plymouth
  become: true
  community.general.pacman:
    name:
      - plymouth-git
      # - plymouth-theme-...
  notify:
    - Run dracut

- name: Copying plymouth configuration
  become: true
  ansible.builtin.copy:
    dest: /etc/plymouth/plymouthd.conf
    group: root
    mode: "0644"
    owner: root
    src: plymouthd.conf
  notify:
    - Run dracut

- name: Copying dracut kernel commandline configuration
  become: true
  ansible.builtin.template:
    dest: /etc/dracut.conf.d/cmdline.conf
    group: root
    mode: "0644"
    owner: root
    src: cmdline.conf.j2
  notify:
    - Run dracut

- name: Installing imagemagick # for bootsplash conversion
  become: true
  community.general.pacman:
    name: imagemagick
    state: present

- name: Copying (and converting) bootsplash image
  become: true
  ansible.builtin.command: >
    magick {{ playbook_dir }}/roles/base/files/bootsplash.png
    -background black -flatten /etc/finelli/bootsplash.bmp
  args:
    creates: /etc/finelli/bootsplash.bmp

- name: Copying custom dracut configuration
  become: true
  ansible.builtin.copy:
    dest: /etc/dracut.conf.d/custom.conf
    group: root
    mode: "0644"
    owner: root
    src: dracut.conf
  notify:
    - Run dracut

- name: Copying "/etc/locale.gen"
  become: true
  ansible.builtin.copy:
    dest: /etc/locale.gen
    group: root
    mode: "0644"
    owner: root
    src: locale.gen
  register: locales_list

- name: Running `locale-gen`
  when: locales_list.changed # noqa no-handler
  become: true
  ansible.builtin.command: locale-gen
  register: localegen
  changed_when: localegen.rc == 0
  failed_when: localegen.rc != 0

- name: Copying "/etc/locale.conf"
  become: true
  ansible.builtin.template:
    dest: /etc/locale.conf
    group: root
    mode: "0644"
    owner: root
    src: locale.conf.j2

- name: Installing bootstrap packages
  become: true
  community.general.pacman:
    name:
      - btrfs-progs
      - cryptsetup
      - dosfstools
      - e2fsprogs
      - efibootmgr
      - elfutils
      - exfat-utils
      - f2fs-tools
      - lvm2
      - mdadm
      - ntfs-3g
      - os-prober
      - usbutils
    state: present

- name: Installing video and input drivers
  become: true
  community.general.pacman:
    name:
      - mesa
      - xf86-input-libinput
    state: present

- name: Installing Intel microcode
  become: true
  when: "'GenuineIntel' in ansible_processor"
  community.general.pacman:
    name: intel-ucode
    state: present

- name: Installing AMD microcode
  become: true
  when: "'AuthenticAMD' in ansible_processor"
  community.general.pacman:
    name: amd-ucode
    state: present

- name: Enabling the systemd-boot updater
  when: mmode != 'setup'
  ansible.builtin.systemd:
    enabled: true
    name: systemd-boot-update.service

- name: Creating "sudo" group
  become: true
  ansible.builtin.group:
    gid: 27 # like in debian
    name: sudo
    state: present
    system: true

- name: Adding mario to sudo group
  become: true
  ansible.builtin.user:
    append: true
    groups: sudo
    user: "{{ whoami }}"

- name: Copying sudo configuration
  become: true
  ansible.builtin.copy:
    dest: /etc/sudoers.d/gsudo
    group: root
    mode: "0440"
    owner: root
    src: sudoer
    validate: visudo -cf %s

- name: Configuring makepkg and pacman
  ansible.builtin.include_tasks: pacman.yml

- name: Installing ansible-gpg-key (from supermario repo)
  become: true
  community.general.pacman:
    name: ansible-gpg-key-git
    state: present

- name: Installing pikaur
  kewlfft.aur.aur:
    name: pikaur
    state: present

- name: Installing networking tools
  become: true
  community.general.pacman:
    name:
      - dialog
      - easy-rsa
      - iw
      - iwd
      - netctl
      - networkmanager
      - networkmanager-openvpn
      - wireless-regdb
      - wpa_supplicant
    state: present

- name: Enabling Network Manager service
  become: true
  ansible.builtin.systemd:
    enabled: true
    name: NetworkManager.service

- name: Installing inetutils # for `hostname`
  become: true
  community.general.pacman:
    name: inetutils
    state: present

- name: Copying wireless-regdom configuration
  become: true
  ansible.builtin.template:
    dest: /etc/conf.d/wireless-regdom
    group: root
    mode: "0644"
    owner: root
    src: wireless-regdom.j2

- name: Installing packages from old "base" group
  become: true
  community.general.pacman:
    name:
      - bash-completion
      - logrotate
      - man-db
      - man-pages
      - nano
      - perl
      - s-nail
      - texinfo
      - vi
    state: present

- name: Installing ansible and dependencies
  become: true
  community.general.pacman:
    name:
      - ansible
      - git
      - pyalpm
    state: present

- name: Installing optional ansible dependencies
  become: true
  community.general.pacman:
    name:
      - python-argcomplete
      - python-dnspython
      - python-jmespath
      - python-keyring
      - python-ldap
      - python-pip
      - python-pyopenssl
      - python-systemd
    state: present

- name: Install "everywhere" packages
  become: true
  community.general.pacman:
    name:
      - lynx
      - rsync
      - vim
      - vim-spell-en
      - vim-spell-es
      - vim-spell-fr
      - vim-spell-it
      - wget
    state: present

- name: Uninstalling packages
  become: true
  community.general.pacman:
    name:
      - ansible-aur
      - archuseriso
      - epson-inkjet-printer-escpr
      - epson-inkjet-printer-escpr2
      - keepass
      - python-py-cpuinfo
      - xf86-video-amdgpu
      - xf86-video-ati
      - xf86-video-intel
      - xf86-video-vesa
      - aspell
      - aspell-en
      - aspell-es
      - aspell-fr
      - aspell-it
      - pidgin
      - pidgin-otr
      - purple-plugin-pack
    state: absent

- name: Configuring a simple firewall
  ansible.builtin.include_tasks: firewall.yml
