---
- name: ensure baseline archlinux system
  become: true
  pacman:
    name:
      - base
      - base-devel
      - linux
      - linux-firmware
      - posix

- name: install bootstrap packages
  become: true
  pacman:
    name:
      - grub
      - efibootmgr
      - btrfs-progs
      - dosfstools
      - ntfs-3g
      - e2fsprogs
      - exfat-utils
      - os-prober
      - lvm2
      - cryptsetup
      - mdadm
      - usbutils

- name: install video and input drivers
  become: true
  pacman:
    name:
      - xf86-video-vesa
      - xf86-input-libinput

- name: install intel video drivers
  become: true
  when: gcard == 'intel'
  pacman:
    name:
      - xf86-video-intel

- name: install amd video drivers
  become: true
  when: gcard == 'amd'
  pacman:
    name:
      - xf86-video-ati
      - xf86-video-amdgpu

- name: install intel microcode
  become: true
  when: ansible_processor[1] == 'GenuineIntel'
  pacman: name=intel-ucode

- name: install ansible dependencies
  become: true
  pacman:
    name:
      - ansible
      - git
      - pyalpm

- name: ensure sudoer rule
  become: true
  copy:
    dest: /etc/sudoers.d/mario
    owner: root
    group: root
    mode: 0440
    src: sudoer
    validate: 'visudo -cf %s'

- name: install pikaur
  aur: name=pikaur

- name: install ansible-aur
  aur:
    name: ansible-aur-git
    use: pikaur # extra_args cannot be used in auto mode
    extra_args: --overwrite /usr/share/ansible/plugins/modules/aur.py

- name: install ansible-gpg-key
  aur: name=ansible-gpg-key-git

- name: install ansible-gsetting
  aur: name=ansible-gsetting-git

- include: pacman.yml

- name: install networking tools
  become: true
  pacman:
    name:
      - iw
      - iwd
      - dialog
      - wpa_supplicant
      - easy-rsa
      - networkmanager
      - networkmanager-openvpn
      - crda
      - inetutils
      - netctl

- name: install old base group packages
  become: true
  pacman:
    name:
      - logrotate
      - man-db
      - nano
      - perl
      - s-nail
      - texinfo
      - vi
      - man-pages
      - bash-completion

- name: install audio packages
  become: true
  pacman:
    name:
      - alsa-utils
      - alsa-plugins
      - pulseaudio
      - pulseaudio-alsa
      - pavucontrol

- name: install xorg
  become: true
  pacman:
    name:
      - xorg-server
      - xorg-apps

- name: install desktop environment (xfce)
  become: true
  pacman:
    name:
      - xfce4
      - xfce4-goodies
      - lightdm
      - lightdm-gtk-greeter
      - network-manager-applet
      - accountsservice
      - xdg-user-dirs
      - gvfs
      - gvfs-afc
      - gvfs-mtp
      - gnome-keyring
      - seahorse

- name: install lightdm configuration
  become: true
  template:
    src: lightdm.conf.j2
    dest: /etc/lightdm/lightdm.conf
    owner: root
    group: root
    mode: 0644

- name: enable lightdm
  become: true
  systemd: name=lightdm.service enabled=yes

- name: enable network manager
  become: true
  systemd: name=NetworkManager.service enabled=yes

- name: install base packages
  become: true
  pacman:
    name:
      - firefox
      - firefox-i18n-en-us
      - firefox-i18n-es-es
      - firefox-i18n-fr
      - firefox-i18n-it
      - openssh
      - vim
      - vim-spell-de
      - vim-spell-en
      - vim-spell-es
      - vim-spell-fr
      - vim-spell-it
      - lynx
      - rsync
      - wget
      - xsel

- include: apps.yml
- include: cli.yml
- include: dev.yml
- include: printing.yml
