---
- name: install wine
  when:
    - "multilib == 'true'"
    - "mtype == 'personal' or mtype == 'media'"
  become: true
  pacman:
    name:
      - wine
      - wine-mono
      - wine-gecko
      - winetricks

- name: install lib32 libraries
  when: "multilib == 'true' and (mtype == 'personal' or mtype == 'media')"
  become: true
  pacman:
    name:
      - lib32-libpulse
      - lib32-alsa-plugins

- name: install picard
  when: "mtype == 'personal' or mtype == 'media'"
  become: true
  pacman: name=picard

- name: install other music applications
  when: "mtype == 'personal' or mtype == 'media'"
  aur:
    name:
      - foobar2000
      - mp3tag
