---
- name: install makepkg configuration
  become: true
  template:
    src: makepkg.conf.j2
    dest: /etc/makepkg.conf
    owner: root
    group: root
    mode: 0644

- name: install pacman configuration
  become: true
  template:
    src: pacman.conf.j2
    dest: /etc/pacman.conf
    owner: root
    group: root
    mode: 0644

- name: install extra pacman-related packages
  become: true
  pacman:
    name:
      - expac
      - asp
