---
- name: Copying makepkg configuration
  become: true
  ansible.builtin.template:
    dest: /etc/makepkg.conf
    group: root
    mode: "0644"
    owner: root
    src: makepkg.conf.j2

- name: Copying pacman configuration
  become: true
  ansible.builtin.template:
    dest: /etc/pacman.conf
    group: root
    mode: "0644"
    owner: root
    src: pacman.conf.j2
  register: pacman_config

- name: Adding "supermario" key to pacman keyring and signing it locally
  become: true
  community.general.pacman_key:
    id: C3CD75B002978A8468CA7B1F6C3ADDDE36FDA306
    state: present
    url: https://finelli.pub/36FDA306.asc
  register: supermario_key

- name: Running `pacman -Syyu` # (because the repositories changed)
  when: supermario_key.changed or pacman_config.changed # noqa no-handler
  become: true
  community.general.pacman:
    force: true
    update_cache: true
    upgrade: true

- name: Installing extra pacman-related packages
  become: true
  community.general.pacman:
    name:
      - asp
      - aurpublish
      - devtools
      - expac
      - namcap
      - pacman-contrib
      - pacutils
      - pkgfile
    state: present

- name: Installing reflector
  become: true
  community.general.pacman:
    name: reflector
    state: present

- name: Copying reflector configuration
  become: true
  ansible.builtin.copy:
    dest: /etc/xdg/reflector/reflector.conf
    group: root
    mode: "0644"
    owner: root
    src: reflector.conf
  register: reflector_config

- name: Enabling reflector cron
  become: true
  ansible.builtin.systemd:
    enabled: true
    name: reflector.timer

- name: Running reflector on-demand
  when: mmode != 'setup' and reflector_config.changed
  become: true
  ansible.builtin.systemd:
    name: reflector.service
    state: started

- name: Running `pacman -Syyu` # because the mirrorlist changed
  when: reflector_config.changed # noqa no-handler
  become: true
  community.general.pacman:
    force: true
    update_cache: true
    upgrade: true
