---
- name: install makepkg configuration
  become: true
  ansible.builtin.template:
    src: makepkg.conf.j2
    dest: /etc/makepkg.conf
    owner: root
    group: root
    mode: 0644

- name: install pacman configuration
  become: true
  ansible.builtin.template:
    src: pacman.conf.j2
    dest: /etc/pacman.conf
    owner: root
    group: root
    mode: 0644
  register: pacman_config

- name: add supermario key to keyring and locally sign it
  become: true
  community.general.pacman_key:
    id: C3CD75B002978A8468CA7B1F6C3ADDDE36FDA306
    url: https://finelli.pub/36FDA306.asc
  register: supermario_key

- name: run pacman -Syyu because the repositories changed
  when: supermario_key.changed or pacman_config.changed # noqa no-handler
  become: true
  community.general.pacman: update_cache=true upgrade=true force=true

- name: install extra pacman-related packages
  become: true
  community.general.pacman:
    name:
      - expac
      - asp
      - devtools
      - namcap
      - pacman-contrib
      - pacutils
      - pkgfile
      - aurpublish

- name: install reflector
  become: true
  community.general.pacman: name=reflector

- name: install reflector config
  become: true
  ansible.builtin.copy:
    src: reflector.conf
    dest: /etc/xdg/reflector/reflector.conf
    owner: root
    group: root
    mode: 0644
  register: reflector_config

- name: enable reflector timer
  become: true
  ansible.builtin.systemd: name=reflector.timer enabled=true

- name: run reflector on-demand
  when: mmode != 'setup' and reflector_config.changed
  become: true
  ansible.builtin.systemd: name=reflector.service state=started

- name: run pacman -Syyu because the mirrorlist changed
  when: reflector_config.changed # noqa no-handler
  become: true
  community.general.pacman: update_cache=true upgrade=true force=true
