---
- name: Creating systemd-timesyncd configuration directory
  become: true
  ansible.builtin.file:
    group: root
    mode: "0755"
    owner: root
    path: /etc/systemd/timesyncd.conf.d
    state: directory

- name: Copying systemd-timesyncd configuration
  become: true
  ansible.builtin.copy:
    dest: /etc/systemd/timesyncd.conf.d/90-finelli.conf
    group: root
    mode: "0644"
    owner: root
    src: timesyncd.conf
  notify:
    - Restart systemd-timesyncd

- name: Enabling systemd-timesyncd service
  become: true
  ansible.builtin.systemd:
    enabled: true
    name: systemd-timesyncd.service

- name: Creating systemd-resolved configuration directory
  become: true
  ansible.builtin.file:
    group: root
    mode: "0755"
    owner: root
    path: /etc/systemd/resolved.conf.d
    state: directory

- name: Copying systemd-resolved configuration
  become: true
  ansible.builtin.template:
    dest: /etc/systemd/resolved.conf.d/90-finelli.conf
    group: root
    mode: "0644"
    owner: root
    src: resolved.conf.j2
  notify:
    - Restart systemd-resolved

- name: Linking systemd-resolved stub resolver to /etc/resolv.conf
  become: true
  when: mmode != 'setup' # don't run before first reboot
  ansible.builtin.file:
    dest: /etc/resolv.conf
    force: true
    src: /run/systemd/resolve/stub-resolv.conf
    state: link

- name: Enabling systemd-resolved
  become: true
  ansible.builtin.systemd:
    enabled: true
    name: systemd-resolved.service
