---
- name: Installing cloud commandline tools
  when: mtype == 'personal'
  become: true
  community.general.pacman:
    name:
      - aws-cli
      - doctl
      - google-cloud-sdk
      - python-magic
    state: present

- name: Installing main devops tools
  when: mtype == 'personal'
  become: true
  community.general.pacman:
    name:
      - newrelic-cli
      - sops
      - terraform
    state: present

- name: Installing kubectl
  when: mtype == 'personal' or mtype == 'work'
  become: true
  community.general.pacman:
    name: kubectl
    state: present

- name: Installing kubernetes tools
  when: mtype == 'personal'
  become: true
  community.general.pacman:
    name:
      - helm
      - helm-diff
      - helm-gcs
      - helm-s3
      - helm-secrets
      - helmfile
      - pluto
      - popeye
    state: present

- name: Installing kubernetes tools (part two)
  when: mtype == 'personal' or mtype == 'work'
  become: true
  community.general.pacman:
    name:
      - kubectx
      - lens
    state: present

- name: Installing helm plugins
  when: mtype == 'personal'
  kubernetes.core.helm_plugin:
    plugin_path: /usr/lib/helm/plugins/{{ item }}
  loop:
    - diff
    - gcs
    - s3
    - secrets
