---
- name: install cloud dependencies
  when: mtype == 'personal'
  become: true
  pacman:
    name:
      - aws-cli
      - python-magic
      - google-cloud-sdk
      - doctl

- name: install devops tools
  when: mtype == 'personal'
  become: true
  pacman:
    name:
      - terraform
      - packer
      - sops
      - newrelic-cli

- name: install kubectl
  when: mtype == 'personal' or mtype == 'work'
  become: true
  pacman: name=kubectl

- name: install kubernetes tools
  when: mtype == 'personal'
  become: true
  pacman:
    name:
      - helm
      - helmfile
      - pluto
      - popeye
      - helm-secrets
      - helm-diff
      - helm-gcs
      - helm-s3

- name: install kubernetes tools pt. ii
  when: mtype == 'personal' or mtype == 'work'
  become: true
  pacman:
    name:
      - kubectx
      - lens

- name: install helm plugins
  when: mtype == 'personal'
  kubernetes.core.helm_plugin:
    plugin_path: /usr/lib/helm/plugins/{{ item }}
  loop:
    - diff
    - gcs
    - s3
    - secrets
