---
- name: Installing cloud commandline tools
  when: mtype == 'personal'
  become: true
  community.general.pacman:
    name:
      - aws-cli
      - doctl
      - python-magic
    state: present

- name: Installing google-cloud-cli
  when: mtype == 'personal' or mtype == 'work'
  become: true
  community.general.pacman:
    name: google-cloud-cli
    state: present

- name: Installing main devops tools
  when: mtype == 'personal'
  become: true
  community.general.pacman:
    name:
      - sops
      - opentofu
    state: present

- name: Installing kubectl
  when: mtype == 'personal' or mtype == 'work'
  become: true
  community.general.pacman:
    name: kubectl
    state: present

- name: Installing kubernetes tools
  when: mtype == 'personal'
  become: true
  community.general.pacman:
    name:
      - helm
      - helm-diff
      - helm-s3
      - helm-secrets
      - pluto
      - popeye
    state: present

- name: Installing kubernetes tools (part two)
  when: mtype == 'personal' or mtype == 'work'
  become: true
  community.general.pacman:
    name:
      - k9s
      - kubectx
    state: present

- name: Installing helm plugins
  when: mtype == 'personal'
  kubernetes.core.helm_plugin:
    plugin_path: /usr/lib/helm/plugins/{{ item }}
  loop:
    - diff
    - s3
    - secrets

- name: Installing Remmina
  when: mtype == 'personal' or mtype == 'work'
  become: true
  community.general.pacman:
    name:
      - remmina
    state: present
