---
- name: Install cloud dependencies
  when: mtype == 'personal'
  become: true
  community.general.pacman:
    name:
      - aws-cli
      - python-magic
      - google-cloud-sdk
      - doctl

- name: Install devops tools
  when: mtype == 'personal'
  become: true
  community.general.pacman:
    name:
      - terraform
      - packer
      - sops
      - newrelic-cli

- name: Install kubectl
  when: mtype == 'personal' or mtype == 'work'
  become: true
  community.general.pacman:
    name: kubectl

- name: Install kubernetes tools
  when: mtype == 'personal'
  become: true
  community.general.pacman:
    name:
      - helm
      - helmfile
      - pluto
      - popeye
      - helm-secrets
      - helm-diff
      - helm-gcs
      - helm-s3

- name: Install kubernetes tools pt. ii
  when: mtype == 'personal' or mtype == 'work'
  become: true
  community.general.pacman:
    name:
      - kubectx
      - lens

- name: Install helm plugins
  when: mtype == 'personal'
  kubernetes.core.helm_plugin:
    plugin_path: /usr/lib/helm/plugins/{{ item }}
  loop:
    - diff
    - gcs
    - s3
    - secrets
