---
- name: install firefox developer edition
  when: mtype != 'media' and mtype != 'server'
  become: true
  pacman: name=firefox-developer-edition

- name: install main development packages
  when: mtype == 'personal'
  become: true
  pacman:
    name:
      - imagemagick
      - geckodriver

- name: download extra editors
  when: mtype == 'personal'
  aur:
    name:
      - sublime-text-4
      - rubymine

- name: install latex packages
  when: mtype != 'media'
  become: true
  pacman:
    name:
      - texlive-most
      - texlive-lang

- name: install docker
  when: mtype != 'media'
  become: true
  pacman:
    name:
      - docker
      - docker-compose

- name: install hadolint
  when: mtype == 'personal'
  aur:
    name:
      - hadolint

- name: install virtualbox
  when: mtype != 'media'
  become: true
  pacman:
    name:
      - vagrant
      - virtualbox
      - virtualbox-host-modules-arch
      - virtualbox-guest-iso

- name: install command line utilities
  when: mtype != 'media'
  become: true
  pacman:
    name:
      - jpegoptim
      - optipng
      - shellcheck
      - shfmt

- name: install go
  when: mtype != 'media'
  become: true
  pacman:
    name:
      - go
      - go-tools

- name: install rust
  when: mtype != 'media'
  become: true
  pacman:
    name:
      - rust
      - cargo-outdated

- name: install cargo extensions
  when: mtype != 'media'
  aur:
    name:
      - cargo-about

- name: install postfix
  when: mtype != 'media'
  become: true
  pacman: name=postfix

- include: php.yml
- include: nodejs.yml
- include: ruby.yml
- include: cloud.yml
- include: devops.yml
