---
- name: Install firefox developer edition
  when: mtype != 'media' and mtype != 'server'
  become: true
  community.general.pacman:
    name: firefox-developer-edition

- name: Install main development packages
  when: mtype == 'personal'
  become: true
  community.general.pacman:
    name:
      - imagemagick
      - geckodriver

- name: Download extra editors
  when: mtype == 'personal'
  kewlfft.aur.aur:
    name:
      - sublime-text-4
      - rubymine

- name: Install latex packages
  when: mtype == 'personal'
  become: true
  community.general.pacman:
    name:
      - texlive-most
      - texlive-lang

- name: Install docker
  when: mtype != 'media'
  become: true
  community.general.pacman:
    name:
      - docker
      - docker-compose

- name: Install virtualbox
  when: mtype != 'media'
  become: true
  community.general.pacman:
    name:
      - virtualbox
      - virtualbox-host-modules-arch
      - virtualbox-guest-iso

# TODO: sudo usermod -aG libvirt mario
- name: Install virt-manager
  when: mtype != 'media'
  become: true
  community.general.pacman:
    name:
      - virt-manager
      - qemu-desktop
      - libvirt
      - edk2-ovmf
      - dnsmasq
      - swtpm

- name: Install libvirtd configuration
  when: mtype != 'media'
  become: true
  ansible.builtin.copy:
    dest: /etc/libvirt/libvirtd.conf
    owner: root
    group: root
    mode: "0644"
    src: libvirtd.conf

- name: Install libvirtd qemu configuration
  when: mtype != 'media'
  become: true
  ansible.builtin.template:
    dest: /etc/libvirt/qemu.conf
    owner: root
    group: root
    mode: "0644"
    src: qemu.conf.j2

- name: Install command line utilities
  when: mtype != 'media'
  become: true
  community.general.pacman:
    name:
      - cui
      - hugo
      - jpegoptim
      - optipng
      - shellcheck
      - shfmt

- name: Install go
  when: mtype != 'media'
  become: true
  community.general.pacman:
    name:
      - go
      - go-tools

- name: Install rust
  when: mtype != 'media'
  become: true
  community.general.pacman:
    name:
      - rust
      - cargo-about
      - cargo-outdated

- name: Install redis
  when: mtype == 'personal'
  become: true
  community.general.pacman:
    name: redis

- name: Install postgresql
  when: mtype == 'personal'
  become: true
  community.general.pacman:
    name: postgresql

- name: Install postfix
  when: mtype != 'media'
  become: true
  community.general.pacman:
    name: postfix

- name: Install neovim
  when: mtype != 'media'
  become: true
  community.general.pacman:
    name: neovim

- name: Install asciinema
  when: mtype == 'personal'
  become: true
  community.general.pacman:
    name:
      - asciinema
      - asciinema-agg

- name: Install fastfoto stuff
  when: mtype != 'media'
  become: true
  community.general.pacman:
    name:
      - cloudflared
      - cobra-cli
      - goose
      - perl-image-exiftool
      - perl-archive-zip
      - sqlc

# - name: install fastfoto stuff from aur
#   when: mtype != 'media'
#   kewlfft.aur.aur:
#     name:

- name: Install nodejs and tools
  ansible.builtin.include_tasks: nodejs.yml

- name: Install ruby and tools
  ansible.builtin.include_tasks: ruby.yml

- name: Install devops tools
  ansible.builtin.include_tasks: devops.yml
