---
- name: Installing Firefox Developer Edition
  when: mtype != 'media'
  become: true
  community.general.pacman:
    name: firefox-developer-edition
    state: present

- name: Installing geckodriver
  when: mtype == 'personal'
  become: true
  community.general.pacman:
    name: geckodriver
    state: present

- name: Installing LaTeX packages
  when: mtype == 'personal'
  become: true
  community.general.pacman:
    name:
      - texlive-lang
      - texlive-meta
    state: present

# TODO: switch to podman
- name: Installing docker
  when: mtype != 'media'
  become: true
  community.general.pacman:
    name:
      - docker
      - docker-compose
    state: present

- name: Installing Virtualbox
  when: mtype != 'media'
  become: true
  community.general.pacman:
    name:
      - virtualbox
      - virtualbox-guest-iso
      - virtualbox-host-modules-arch
    state: present

- name: Installing virt-manager
  when: mtype != 'media'
  become: true
  community.general.pacman:
    name:
      - dnsmasq
      - edk2-ovmf
      - libvirt
      - qemu-desktop
      - swtpm
      - virt-manager
    state: present

- name: Adding mario to libvirt group
  become: true
  ansible.builtin.user:
    append: true
    groups: libvirt
    user: "{{ whoami }}"

- name: Copying libvirtd configuration
  when: mtype != 'media'
  become: true
  ansible.builtin.copy:
    dest: /etc/libvirt/libvirtd.conf
    group: root
    mode: "0644"
    owner: root
    src: libvirtd.conf

- name: Copying libvirtd QEMU configuration
  when: mtype != 'media'
  become: true
  ansible.builtin.template:
    dest: /etc/libvirt/qemu.conf
    group: root
    mode: "0644"
    owner: root
    src: qemu.conf.j2

- name: Installing main commandline utilities
  when: mtype != 'media'
  become: true
  community.general.pacman:
    name:
      - cui
      - hugo
      - jpegoptim
      - optipng
      - prettier
      - shellcheck
      - shfmt
    state: present

- name: Installing go
  when: mtype != 'media'
  become: true
  community.general.pacman:
    name:
      - go
      - go-tools
      - gopls
      - staticcheck
    state: present

- name: Installing rust
  when: mtype != 'media'
  become: true
  community.general.pacman:
    name:
      - cargo-about
      - cargo-outdated
      - rust
    state: present

- name: Installing redis
  when: mtype == 'personal'
  become: true
  community.general.pacman:
    name: redis
    state: present

- name: Installing PostgreSQL
  when: mtype == 'personal'
  become: true
  community.general.pacman:
    name: postgresql
    state: present

- name: Installing postfix
  when: mtype != 'media'
  become: true
  community.general.pacman:
    name: postfix
    state: present

- name: Installing neovim
  when: mtype != 'media'
  become: true
  community.general.pacman:
    name: neovim
    state: present

- name: Installing asciinema
  when: mtype == 'personal'
  become: true
  community.general.pacman:
    name:
      - asciinema
      - asciinema-agg
    state: present

- name: Installing fastfoto dependencies
  when: mtype == 'personal'
  become: true
  community.general.pacman:
    name:
      - cloudflared
      - cobra-cli
      - goose
      - perl-archive-zip
      - perl-image-exiftool
      - sqlc
    state: present

- name: Installing nodejs and tools
  ansible.builtin.include_tasks: nodejs.yml

- name: Installing ruby and tools
  ansible.builtin.include_tasks: ruby.yml

- name: Installing devops tools
  ansible.builtin.include_tasks: devops.yml
