---
- name: Installing Firefox Developer Edition
  when: mtype != 'media'
  become: true
  community.general.pacman:
    name: firefox-developer-edition
    state: present

- name: Installing ghostty
  when: mtype != 'media'
  become: true
  community.general.pacman:
    name: ghostty
    state: present

- name: Installing LaTeX packages
  when: mtype == 'personal'
  become: true
  community.general.pacman:
    name:
      - texlive-lang
      - texlive-meta
    state: present

- name: Installing mise
  when: mtype != 'media'
  become: true
  community.general.pacman:
    name: mise
    state: present

# TODO: switch to podman
- name: Installing docker
  when: mtype != 'media'
  become: true
  community.general.pacman:
    name:
      - dive
      - docker
      - docker-compose
      - lazydocker
    state: present

- name: Installing Virtualbox
  when: mtype != 'media'
  become: true
  community.general.pacman:
    name:
      - virtualbox
      - virtualbox-guest-iso
      - virtualbox-host-modules-arch
    state: present

- name: Installing main commandline utilities
  when: mtype != 'media'
  become: true
  community.general.pacman:
    name:
      - atac
      - glow
      - hugo
      - jpegoptim
      - just
      - openbsd-netcat
      - optipng
      - shellcheck
      - shfmt
    state: present

- name: Installing secondary commandline utilities
  when: mtype != 'media'
  become: true
  community.general.pacman:
    name:
      - dasel
      - dust
      - hurl
      - hyperfine
      - iprange
      - tokei
      - ugrep
    state: present

- name: Installing go
  when: mtype != 'media'
  become: true
  community.general.pacman:
    name:
      - delve
      - go
      - go-critic
      - go-tools
      - gopls
      - staticcheck
    state: present

- name: Installing rust
  when: mtype != 'media'
  become: true
  community.general.pacman:
    name:
      - cargo-about
      - cargo-outdated
      - rust
      - rust-analyzer
    state: present

- name: Installing valkey
  when: mtype == 'personal'
  become: true
  community.general.pacman:
    name: valkey
    state: present

- name: Installing PostgreSQL
  when: mtype == 'personal'
  become: true
  community.general.pacman:
    name: postgresql
    state: present

- name: Installing postfix
  when: mtype != 'media'
  become: true
  community.general.pacman:
    name: postfix
    state: present

- name: Installing language servers
  when: mtype != 'media'
  become: true
  community.general.pacman:
    name:
      - python-lsp-server
    state: present

- name: Installing asciinema
  when: mtype == 'personal'
  become: true
  community.general.pacman:
    name:
      - asciinema
      - asciinema-agg
    state: present

- name: Installing fastfoto dependencies
  when: mtype == 'personal'
  become: true
  community.general.pacman:
    name:
      - cloudflared
      - cobra-cli
      - goose
      - perl-archive-zip
      - perl-image-exiftool
      - sqlc
    state: present

- name: Installing vinovoto dependencies
  when: mtype == 'personal'
  become: true
  community.general.pacman:
    name:
      - mdq
      - templ
      - ttf-iosevka
      - typst
      - wgo

- name: Installing nodejs
  when: mtype == 'personal'
  become: true
  community.general.pacman:
    name:
      - nodejs
      - npm
      - pnpm
    state: present

- name: Installing ruby and tools
  ansible.builtin.include_tasks: ruby.yml

- name: Installing devops tools
  ansible.builtin.include_tasks: devops.yml
