---
- name: Installing nodejs
  when: mtype == 'personal'
  become: true
  community.general.pacman:
    name:
      - nodejs
      - npm
    state: present

- name: Installing nodejs packages
  when: mtype == 'personal'
  become: true
  community.general.pacman:
    name:
      - nodejs-mjml
      - nodejs-n
      - nodejs-pug-cli
    state: present
