---
- name: install nodejs
  when: "mtype == 'personal'"
  become: true
  pacman:
    name:
      - nodejs
      - npm

- name: install n node version manager
  when: "mtype == 'personal'"
  aur: name=nodejs-n

- name: install other nodejs packages
  when: "mtype == 'personal'"
  aur:
    name:
      - nodejs-autoprefixer
      - nodejs-clean-css-cli
      - nodejs-pug-cli
      - nodejs-mjml
