---
- name: Install nodejs
  when: mtype == 'personal'
  become: true
  community.general.pacman:
    name:
      - nodejs
      - npm

- name: Install nodejs packages
  when: mtype == 'personal'
  become: true
  community.general.pacman:
    name:
      - nodejs-n
      - nodejs-pug-cli
      - nodejs-mjml
