---
- name: Installing ruby
  when: mtype == 'personal'
  become: true
  community.general.pacman:
    name:
      - ruby
      - ruby-bundler
    state: present

- name: Installing ruby packages
  when: mtype == 'personal'
  become: true
  community.general.pacman:
    name:
      - chruby
      - ruby-install
      - ruby-pry
    state: present
