---
- name: Install ruby
  when: mtype == 'personal'
  become: true
  community.general.pacman:
    name:
      - ruby
      - ruby-rake
      - ruby-rdoc
      - ruby-bundler

- name: Install ruby packages
  when: mtype == 'personal'
  become: true
  community.general.pacman:
    name:
      - ruby-install
      - ruby-pry
      - ruby-rubocop
      - chruby
