---
- name: Adding APT pin for backports packages
  ansible.builtin.template:
    dest: /etc/apt/preferences.d/media
    group: root
    mode: "0644"
    owner: root
    src: media.j2
  register: media_apt_pin

- name: Installing media packages
  ansible.builtin.apt:
    name:
      - cksfv
      - gallery-dl
      - keepassxc
      - sabnzbdplus
      - torbrowser-launcher
      - transmission
      - vlc
      - yt-dlp
    state: present
    update_cache: "{{ media_apt_pin.changed }}"
