---
- name: Adding APT pin for backports packages
  ansible.builtin.template:
    dest: /etc/apt/preferences.d/media
    group: root
    mode: "0644"
    owner: root
    src: media.j2

- name: Installing media packages
  ansible.builtin.apt:
    name:
      - cksfv
      - magic-wormhole
      - keepassxc
      - sabnzbdplus
      - torbrowser-launcher
      - transmission
      - vlc
    state: present

- name: Installing media packages from backports
  ansible.builtin.apt:
    default_release: "{{ ansible_distribution_release }}-backports"
    name:
      - gallery-dl
      - yt-dlp
    state: present
