tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
brew "ansible"
brew "ansible-lint"
brew "awscli"
brew "bash"
brew "bash-completion"
brew "cfssl"
brew "chruby"
brew "fish"
brew "chruby-fish"
brew "coreutils"
brew "curl"
brew "go"
brew "dep"
brew "gawk"
brew "geckodriver"
brew "git"
brew "git-crypt"
brew "gnupg"
brew "google-authenticator-libpam"
brew "graphviz"
brew "grep"
brew "gtk+3"
brew "htop"
brew "jq"
brew "kops"
brew "less"
brew "makepkg"
brew "mariadb"
brew "mas"
brew "nim"
brew "node"
brew "openvpn"
brew "p7zip"
brew "packer"
brew "pinentry-mac"
brew "postgresql"
brew "pwgen"
brew "redis"
brew "ripgrep"
brew "rsync"
brew "ruby-install"
brew "rust"
brew "shellcheck"
brew "stow"
brew "terraform"
brew "thefuck"
brew "tldr"
brew "tmux"
brew "vim"
brew "wget"
brew "yarn"
brew "youtube-dl"
brew "zsh"
cask "1password-cli"
cask "adobe-creative-cloud"
cask "adobe-dng-converter"
cask "apache-directory-studio"
cask "docker"
cask "dropbox"
cask "firefox"
cask "firefox-developer-edition"
cask "gimp"
cask "gnucash"
cask "google-chrome"
cask "google-cloud-sdk"
cask "iterm2"
cask "java8"
cask "keepassxc"
cask "keybase"
cask "libreoffice"
cask "libreoffice-language-pack"
cask "slack"
cask "sonos"
cask "spideroakone"
cask "spotify"
cask "steam"
cask "sublime-text"
cask "thunderbird"
cask "vagrant"
cask "virtualbox"
cask "viscosity"
cask "vlc"
cask "zoomus"
mas "1Password 7", id: 1333542190
mas "Bear", id: 1091189122
mas "Evernote", id: 406056744
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Microsoft Remote Desktop", id: 1295203466
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Skitch", id: 425955336
mas "Textual 7", id: 1262957439
mas "Xcode", id: 497799835
