#!/bin/bash

WORKDIR=$(mktemp -d)
cd $WORKDIR
wget https://aur.archlinux.org/cgit/aur.git/snapshot/package-query.tar.gz
wget https://aur.archlinux.org/cgit/aur.git/snapshot/yaourt.tar.gz
tar -zxvf package-query.tar.gz
tar -zxvf yaourt.tar.gz
cd package-query
makepkg
sudo pacman -U $(ls *.tar.xz)
cd ../yaourt
makepkg
sudo pacman -U $(ls *.tar.xz)
cd
rm -rf $WORKDIR
