#!/bin/bash

WORKDIR=$(mktemp -d)

for package in package-query yaourt; do
    cd $WORKDIR
    wget https://aur.archlinux.org/cgit/aur.git/snapshot/$package.tar.gz
    tar -zxvf $package.tar.gz
    cd $package && makepkg
    sudo pacman -U $(ls *.tar.xz)
done

cd
rm -rf $WORKDIR
