#!/bin/bash

WORKDIR=$(mktemp -d)

for package in package-query yaourt; do
    cd $WORKDIR
    wget https://aur.archlinux.org/cgit/aur.git/snapshot/$package.tar.gz
    tar -zxvf $package.tar.gz
    cd $package && makepkg
    sudo pacman -U $(ls *.tar.xz)
done

cd
rm -rf $WORKDIR

yaourt -S reflector abs pkgcacheclean namcap pkgbuild-introspection downgrade

# only download from https mirrors
sudo reflector --verbose -l 25 -p https --sort rate \
    --save /etc/pacman.d/mirrorlist

PACMAN_TMP=$(mktemp)

# add ILoveCandy configuration option to end of first block of [option]s
# adapted from: http://stackoverflow.com/a/16102492
awk '
  $0 == "[options]" { inOptions = 1 }
  inOptions && $0 == "" {
    print "ILoveCandy"
    inOptions = 0
  }
  1' /etc/pacman.conf > $PACMAN_TMP

sudo mv $PACMAN_TMP /etc/pacman.conf
sudo chown root:root /etc/pacman.conf
sudo chmod 644 /etc/pacman.conf

MAKEPKG_TMP=$(mktemp)
read -p "How many cores to use when compiling packages from source? "
CORES=$((REPLY + 1))
sed "/MAKEFLAGS=\"/s/-j[0-9]/-j$CORES/" /etc/makepkg.conf > $MAKEPKG_TMP
sudo mv $MAKEPKG_TMP /etc/makepkg.conf
sudo chown root:root /etc/makepkg.conf
sudo chmod 644 /etc/makepkg.conf
