#!/bin/bash

source helpers.sh

# pacman -S grub efibootmgr intel-ucode btrfs-progs dosfstools ntfs-3g

# networking
pacman -S iw dialog wpa_supplicant easy-rsa networkmanager{,-openvpn} \
    network-manager-applet

if [[ "no" == $(prompt_yesno "Enable the multilib repository?") ]]; then
    EN_LIB_32=false
else
    EN_LIB_32=true
fi

if [[ $EN_LIB_32 == true ]]; then
    sed -i "/\[multilib\]/s/^#//" /etc/pacman.conf

    # http://stackoverflow.com/a/18622953
    sed -i '/\[multilib\]/!b;n;cInclude = /etc/pacmand.d/mirrorlist' \
        /etc/pacman.conf
fi

read -p "Install Intel or AMD video drivers? "
case $(echo $REPLY | tr '[A-Z]' '[a-z]') in
    intel) DRIVER="xf86-video-intel" ;;
    amd) DRIVER="xf86-video-ati" ;;
    *) exit 1;;
esac

pacman -S $DRIVER xf86-video-vesa xf86-input-synaptics
pacman -S alsa-{utils,plugins}
pacman -S xorg-server{,-utils} xorg-apps
pacman -S xfce4{,-goodies} lightdm{,gtk-greeter} accountsservice \
    xdg-user-dirs gvfs{,-afc,-mtp}

# configure lightdm: don't show the user list; make the user type their name
sed -i "/greeter-hide-users=false/cgreeter-hide-users=true" \
    /etc/lightdm/lightdm.conf
