#!/bin/bash

set -e

# http://stackoverflow.com/a/17695543
function prompt_yesno() {
    read -p "$1 "
    case $(echo $REPLY | tr '[A-Z]' '[a-z]') in
        y|yes) echo "yes" ;;
        *)     echo "no" ;;
    esac
}

pacman -S iw dialog wpa_supplicant easy-rsa networkmanager{,-openvpn} \
    network-manager-applet crda

read -p "Which wireless country (two-letter-code) should we enable? "
sed -i "/WIRELESS_REGDOM=\"$REPLY\"/s/^#//" /etc/conf.d/wireless-regdom

if [[ "yes" == $(prompt_yesno "Enable the multilib repository?") ]]; then
    sed -i "/\[multilib\]/s/^#//" /etc/pacman.conf

    # http://stackoverflow.com/a/18622953
    sed -i '/\[multilib\]/!b;n;cInclude = /etc/pacmand.d/mirrorlist' \
        /etc/pacman.conf
fi

read -p "Install Intel or AMD video drivers? "
case $(echo $REPLY | tr '[A-Z]' '[a-z]') in
    intel) DRIVER="xf86-video-intel" ;;
    amd) DRIVER="xf86-video-ati xf86-video-amdgpu" ;;
    *) exit 1;;
esac

# pacman -S ntp networkmanager-dispatcher-ntpd
# systemctl enable ntpd

pacman -S $DRIVER xf86-video-vesa xf86-input-libinput
pacman -S alsa-{utils,plugins} pulseaudio{,-alsa} pavucontrol
pacman -S xorg-server xorg-apps
pacman -S xfce4{,-goodies} lightdm{,-gtk-greeter} accountsservice \
    xdg-user-dirs gvfs{,-afc,-mtp}

# configure lightdm: don't show the user list; make the user type their name
sed -i "/greeter-hide-users=false/cgreeter-hide-users=true" \
    /etc/lightdm/lightdm.conf

pacman -S wget firefox firefox-i18n-{de,en-us,es-es,fr,it} vim yajl git \
    gnome-keyring seahorse openssh expac stow

systemctl enable lightdm
systemctl enable NetworkManager

pacman -S unbound expat openresolv
curl -o /etc/unbound/root.hints https://www.internic.net/domain/named.cache
sed -i "/#name_servers=127.0.0.1/s/^#//" /etc/resolvconf.conf
resolvconf -u
unbound-control-setup

cat <<EOF >> /etc/unbound/unbound.conf
  root-hints: root.hints
  prefer-ip6: yes
  tcp-upstream: yes
  tls-upstream: yes
  tls-cert-bundle: "/etc/ssl/certs/ca-certificates.crt"

forward-zone:
  name: "."
  forward-addr: 2606:4700:4700::1111#cloudflare-dns.com
  forward-addr: 2606:4700:4700::1001#cloudflare-dns.com
  forward-addr: 1.1.1.1#cloudflare-dns.com
  forward-addr: 1.0.0.1#cloudflare-dns.com
  forward-tls-upstream: yes

remote-control:
  control-enable: yes
  control-interface: 127.0.0.1
  control-port: 8953
  server-key-file: "/etc/unbound/unbound_server.key"
  server-cert-file: "/etc/unbound/unbound_server.pem"
  control-key-file: "/etc/unbound/unbound_control.key"
  control-cert-file: "/etc/unbound/unbound_control.pem"
EOF

cat <<EOF > /etc/systemd/system/root-hints.service
[Unit]
Description=Update root hints for unbound
After=network.target

[Service]
ExecStart=/usr/bin/curl -o /etc/unbound/root.hints \\
    https://www.internic.net/domain/named.cache
EOF

cat <<EOF > /etc/systemd/system/root-hints.timer
[Unit]
Description=Run root.hints monthly

[Timer]
OnCalendar=monthly
Persistent=true

[Install]
WantedBy=timers.target
EOF

cat <<EOF > /etc/NetworkManager/conf.d/rc-manager.conf
[main]
rc-manager=resolvconf
EOF

systemctl enable unbound
systemctl enable root-hints.timer
