#!/bin/bash

set -x -e

if [[ $# -ne 1 ]]; then
    echo 'usage: ./prepare DEVICE'
    exit 1
fi

INSTALL_DISK="$1"

tzselect
hwclock --systohc --utc

for locale in de_DE en_US es_ES fr_FR it_IT; do
    sed -i "/#${locale}.UTF-8 UTF-8/c${locale}.UTF-8 UTF-8" /etc/locale.gen
done

locale-gen

read -p "What language should we use? (e.g. en_US) "
echo "LANG=${REPLY}.UTF-8" > /etc/locale.conf

# can't have a baby without a name
read -p "What's the new hostname? "
hostnamectl set-hostname $REPLY

pacman -S grub efibootmgr intel-ucode btrfs-progs dosfstools ntfs-3g os-prober

# we actually only add encrypt and lvm2 and remove fsck
HOOKS="base udev autodetect modconf block encrypt lvm2 filesystems keyboard"
sed -i "s/^HOOKS=.*/HOOKS=(${HOOKS})/" /etc/mkinitcpio.conf
mkinitcpio -p linux

# awful, i know - basically we need to escape any /'s in the device name when
# passing it into sed or we get an "unknown option to `s'" error
CRYPTD="cryptdevice=$(echo $INSTALL_DISK | sed 's/\//\\\//g')2:crypt"
sed -i "s/^GRUB_CMDLINE_LINUX=.*/GRUB_CMDLINE_LINUX=\"${CRYPTD}\"/" \
    /etc/default/grub
grub-mkconfig -o /boot/grub/grub.cfg

grub-install --target=x86_64-efi --efi-directory=/boot \
    --bootloader-id="Arch Linux" --recheck
