---
- name: Installing desktop packages
  ansible.builtin.apt:
    name:
      - caffeine
      - fonts-firacode
      - fonts-powerline
      - gnome-shell-extensions
      - podman
      - podman-docker
      - tmux
      - zoxide
    state: present

- name: Installing yubikey dependencies
  ansible.builtin.apt:
    name:
      - pcscd
      - scdaemon
    state: present

- name: Installing backup programs
  ansible.builtin.apt:
    name:
      - age
      - awscli
      - borgbackup
      - p7zip-full
      - p7zip-rar
      - pass
      - pass-extension-otp
      - rclone
    state: present

- name: Installing packages from the "supermario" PPA
  ansible.builtin.apt:
    name:
      - fonts-ubuntu-mono-nerd-font
    state: present

- name: Configuring GDM greeter
  ansible.builtin.copy:
    dest: /etc/gdm3/greeter.dconf-defaults
    group: root
    mode: "0644"
    owner: root
    src: greeter.dconf-defaults
