---
- name: Add the mozillateam ppa signing key
  ansible.builtin.apt_key:
    id: 0AB215679C571D1C8325275B9BDB3D89CE49EC21
    keyring: /etc/apt/trusted.gpg.d/mozillateam-ubuntu-ppa.gpg
    keyserver: keyserver.ubuntu.com

- name: Add the mozillateam ppa
  ansible.builtin.template:
    dest: /etc/apt/sources.list.d/mozillateam.list
    group: root
    mode: "0644"
    owner: root
    src: mozillateam.list.j2

- name: Add firefox no-snap pin
  ansible.builtin.copy:
    dest: /etc/apt/preferences.d/firefox-no-snap
    group: root
    mode: "0644"
    owner: root
    src: firefox-no-snap

- name: Install firefox from mozillateam ppa
  ansible.builtin.apt:
    name: firefox
    update_cache: true

- name: Install desktop packages
  ansible.builtin.apt:
    name:
      - caffeine
      - fonts-firacode
      - fonts-powerline
      - gnome-shell-extensions
      - podman
      - podman-docker
      - tmux
      - zoxide

- name: Uninstall docker
  ansible.builtin.apt:
    name:
      - docker-compose
      - docker.io
    state: absent

- name: Install yubikey dependencies
  ansible.builtin.apt:
    name:
      - pcscd
      - scdaemon

- name: Install backup programs
  ansible.builtin.apt:
    name:
      - awscli
      - borgbackup
      - p7zip-full
      - p7zip-rar
      - pass
      - pass-extension-otp
      - rclone

- name: Install packages from my ppa
  ansible.builtin.apt:
    name:
      - fonts-ubuntu-mono-nerd-font
    update_cache: true

- name: Install gdm dconf greeter
  ansible.builtin.copy:
    dest: /etc/gdm3/greeter.dconf-defaults
    group: root
    mode: "0644"
    owner: root
    src: greeter.dconf-defaults
