---
# TODO: we should detect if the case fan is installed
main_fan_enabled_hosts:
  - homepi
  - parkpi
  - raipi
  - tvpi
  - workpi

main_fan_enable_at_degrees_celsius: 70

main_cryptkey_timeout_seconds: 20

main_supermario_repo_host: "https://download.opensuse.org/repositories/home:/\
  mfinelli:/supermario/"

main_attached_storage:
  homepi:
    - label: HOMEPIDATA
      name: homepidata
      mountpoint: /mnt/data
      keyfile: /root/datakey
    - label: MUSICDATA
      name: musicdata
      mountpoint: /mnt/music
      keyfile: /root/musickey
  tvpi:
    - label: TVPIDATA
      name: tvpidata
      mountpoint: /mnt/data
      keyfile: /root/datakey
  workpi:
    - label: ZNCDATA
      name: zncdata
      mountpoint: /var/lib/znc
      keyfile: /root/znckey
      owner: _znc
      group: _znc
    - label: URLWATCHDATA
      name: urlwatchdata
      mountpoint: /var/lib/urlwatch
      keyfile: /root/urlwatchkey
      owner: urlwatch
      group: urlwatch
