---
# TODO: we should detect if the case fan is installed
main_fan_enabled_hosts:
  - homepi
  - parkpi
  - raipi
  - tvpi
  - workpi

main_fan_enable_at_degrees_celsius: 70

main_cryptkey_timeout_seconds: 20

main_attached_storage:
  homepi:
    - label: HOMEPIDATA
      name: homepidata
      mountpoint: /mnt/data
      keyfile: /root/datakey
  tvpi:
    - label: TVPIDATA
      name: tvpidata
      mountpoint: /mnt/data
      keyfile: /root/datakey
