---
- name: Deleting old sources.list format
  ansible.builtin.file:
    path: /etc/apt/sources.list
    state: absent

- name: Copying HTTPS-enabled sources.list
  ansible.builtin.template:
    dest: /etc/apt/sources.list.d/debian.sources
    group: root
    mode: "0664"
    owner: root
    src: debian.sources.j2
  register: base_sources

- name: Deleting old-style sources list
  ansible.builtin.file:
    path: /etc/apt/sources.list
    state: absent

- name: Installing Fast Track keyring
  ansible.builtin.apt:
    name: fasttrack-archive-keyring
    state: present
    update_cache: "{{ base_sources.changed }}"

- name: Adding Fast Track repository
  ansible.builtin.template:
    dest: /etc/apt/sources.list.d/fasttrack.sources
    group: root
    mode: "0664"
    owner: root
    src: fasttrack.sources.j2
  register: base_fasttrack_sources

- name: Updating apt cache for fasttrack repository
  ansible.builtin.apt:
    update_cache: true
  when: base_fasttrack_sources.changed # noqa no-handler

- name: Adding supermario repository
  block:
    - name: Computing repository base url
      ansible.builtin.set_fact:
        base_supermario_repo_full_host: "{{ base_supermario_repo_host }}\
          Debian_{{ ansible_distribution_major_version }}"

    - name: Downloading supermario repository signing key
      ansible.builtin.get_url:
        dest: /etc/apt/keyrings/supermario-archive-keyring.asc
        group: root
        mode: "0644"
        owner: root
        url: "{{ base_supermario_repo_full_host }}/Release.key"
      register: base_supermario_key

    - name: Adding supermario repository signing key
      ansible.builtin.command:
        cmd: >-
          gpg --dearmor -o /usr/share/keyrings/supermario-archive-keyring.gpg
          /etc/apt/keyrings/supermario-archive-keyring.asc
        creates: "{{ base_supermario_key.changed | ternary('',
          '/usr/share/keyrings/supermario-archive-keyring.gpg') | default(omit,
          true) }}"

    - name: Adding supermario repository
      ansible.builtin.template:
        dest: /etc/apt/sources.list.d/supermario.sources
        group: root
        mode: "0644"
        owner: root
        src: supermario.sources.j2
      register: base_supermario_repository

    - name: Updating apt cache for new repository
      ansible.builtin.apt:
        update_cache: true
      when: base_supermario_repository.changed # noqa no-handler
