---
- name: Install unbound
  ansible.builtin.apt:
    name: unbound

- name: Install new resolvconf.conf
  ansible.builtin.copy:
    dest: /etc/resolvconf.conf
    group: root
    mode: "0644"
    owner: root
    src: resolvconf.conf
  notify:
    - Update resolv.conf

- name: Ensure resolvconf forward zone is absent
  ansible.builtin.file:
    path: /etc/unbound/unbound.conf.d/resolvconf_resolvers.conf
    state: absent
  notify:
    - Restart unbound

- name: Install main unbound configuration
  ansible.builtin.copy:
    dest: /etc/unbound/unbound.conf.d/unbound.conf
    group: root
    mode: "0644"
    owner: root
    src: unbound.conf
  notify:
    - Restart unbound

- name: Setup cloudflare as upstream resolver
  ansible.builtin.copy:
    dest: /etc/unbound/unbound.conf.d/cloudflare.conf
    group: root
    mode: "0644"
    owner: root
    src: cloudflare.conf
  notify:
    - Restart unbound

- name: Ensure unbound is started and enabled
  ansible.builtin.systemd:
    enabled: true
    name: unbound.service
    state: started
