---
- name: check if i386 is enabled
  ansible.builtin.shell: dpkg --print-foreign-architectures | grep i386
  register: i386_enabled
  changed_when: i386_enabled.rc == 1
  failed_when: i386_enabled.rc > 1

- name: enable i386 architecture
  ansible.builtin.command: dpkg --add-architecture i386
  when: i386_enabled.rc == 1

- name: add steam repo key
  ansible.builtin.apt_key:
    url: https://repo.steampowered.com/steam/archive/stable/steam.gpg

- name: add steam repository
  ansible.builtin.apt_repository:
    repo: >
      deb [arch=amd64,i386]
      http://repo.steampowered.com/steam/ stable steam
    filename: steam

- name: add steam source repository
  ansible.builtin.apt_repository:
    repo: >
      deb-src [arch=amd64,i386]
      http://repo.steampowered.com/steam/ stable steam
    filename: steam
    update_cache: yes

- name: install steam
  ansible.builtin.apt:
    name:
      - libgl1-mesa-dri:amd64
      - libgl1-mesa-dri:i386
      - libgl1-mesa-glx:amd64
      - libgl1-mesa-glx:i386
      - steam-launcher

- name: add winehq apt key
  ansible.builtin.apt_key:
    url: https://dl.winehq.org/wine-builds/winehq.key
    keyring: /usr/share/keyrings/winehq-archive.gpg

- name: add winehq repository
  ansible.builtin.apt_repository:
    repo: >
      deb [arch=amd64,i386 signed-by=/usr/share/keyrings/winehq-archive.gpg]
      https://dl.winehq.org/wine-builds/ubuntu {{ansible_distribution_release }} main
    filename: winehq
    update_cache: yes

- name: install wine
  ansible.builtin.apt:
    name:
      - winehq-stable
      - fonts-wine
    install_recommends: yes

- name: add lutris ppa signing key
  ansible.builtin.apt_key:
    keyserver: keyserver.ubuntu.com
    id: 82D96E430A1F1C0F0502747E37B90EDD4E3EFAE4
    keyring: /etc/apt/trusted.gpg.d/lutris-team-ubuntu-lutris.gpg

- name: add lutris ppa
  ansible.builtin.apt_repository:
    repo: >
      deb https://ppa.launchpadcontent.net/lutris-team/lutris/ubuntu
      {{ ansible_distribution_release }} main
    filename: lutris

- name: install lutris
  ansible.builtin.apt: name=lutris update_cache=yes
