---
- name: Checking if the i386 architecture is enabled
  ansible.builtin.shell: >
    set -e -o pipefail;
    dpkg --print-foreign-architectures | grep i386
  args:
    executable: /bin/bash
  register: i386_enabled
  changed_when: i386_enabled.rc == 1
  failed_when: i386_enabled.rc > 1

- name: Enabling the i386 architecture
  ansible.builtin.command: dpkg --add-architecture i386
  when: i386_enabled.rc == 1
  register: i386_was_enabled
  changed_when: i386_was_enabled.rc == 0
  failed_when: i386_was_enabled.rc != 0

- name: Adding the Steam repository key
  ansible.builtin.apt_key:
    state: present
    url: https://repo.steampowered.com/steam/archive/stable/steam.gpg

- name: Adding the Steam repository
  ansible.builtin.apt_repository:
    filename: steam
    repo: >
      deb [arch=amd64,i386]
      https://repo.steampowered.com/steam/ stable steam
    update_cache: true

- name: Adding the Steam (source) repository
  ansible.builtin.apt_repository:
    filename: steam
    repo: >
      deb-src [arch=amd64,i386]
      https://repo.steampowered.com/steam/ stable steam
    update_cache: true

- name: Installing Steam
  ansible.builtin.apt:
    name:
      - libgl1-mesa-dri:amd64
      - libgl1-mesa-dri:i386
      - libgl1-mesa-glx:amd64
      - libgl1-mesa-glx:i386
      - steam-launcher
    state: present

- name: Adding the WineHQ signing key
  ansible.builtin.apt_key:
    keyring: /usr/share/keyrings/winehq-archive.gpg
    state: present
    url: https://dl.winehq.org/wine-builds/winehq.key

- name: Adding the WineHQ repository
  ansible.builtin.apt_repository:
    filename: winehq
    repo: >
      deb [arch=amd64,i386 signed-by=/usr/share/keyrings/winehq-archive.gpg]
      https://dl.winehq.org/wine-builds/ubuntu
      {{ ansible_distribution_release }} main
    update_cache: true

- name: Installing wine
  ansible.builtin.apt:
    install_recommends: true
    name:
      - fonts-wine
      # - winehq-stable
      - winehq-staging
    state: present

- name: Adding the Lutris PPA signing key
  ansible.builtin.apt_key:
    id: 82D96E430A1F1C0F0502747E37B90EDD4E3EFAE4
    keyring: /etc/apt/trusted.gpg.d/lutris-team-ubuntu-lutris.gpg
    keyserver: keyserver.ubuntu.com
    state: present

- name: Adding the Lutris PPA repository
  ansible.builtin.apt_repository:
    filename: lutris
    repo: >
      deb https://ppa.launchpadcontent.net/lutris-team/lutris/ubuntu
      {{ ansible_distribution_release }} main
    update_cache: true

- name: Installing Lutris
  ansible.builtin.apt:
    name: lutris
    state: present

- name: Installing Lutris dependencies for running EA Origin
  ansible.builtin.apt:
    name:
      - libasound2-plugins:i386
      - libdbus-1-3:i386
      - libfreetype6:i386
      - libgnutls30:i386
      - libgpg-error0:i386
      - libldap-dev:i386 # libldap-2.4-2:i386
      - libsdl2-2.0-0:i386
      - libxml2:i386
    state: present

- name: Installing Dolphin
  ansible.builtin.apt:
    name: dolphin-emu
    state: present

- name: Installing Virtualbox
  ansible.builtin.apt:
    name:
      - virtualbox
      - virtualbox-guest-additions-iso
    state: present
