#!/bin/bash -e

sudo apt install -y ansible git

wdir="$(mktemp -d)"
sdir="$(pwd)"
cd "$wdir"

git clone https://github.com/mfinelli/arch-install.git
cd arch-install/rpi

ansible-galaxy install -r ../requirements.yml
ansible-playbook --extra-vars fde=true rpi.yml --tags fde

cd "$sdir"
rm -rf "$wdir"

exit 0
