#!/bin/bash -e

sudo apt install -y ansible git

wdir="$(mktemp -d)"
sdir="$(pwd)"
cd "$wdir"

git clone https://github.com/mfinelli/arch-install.git
cd arch-install/rpi

./run.bash

cd "$sdir"
rm -rf "$wdir"

exit 0
