---
- name: Configure RaspberryPi OS
  hosts: localhost
  connection: local
  become: true

  roles:
    - role: fde
      tags: [all, fde]
    - role: main
      tags: [all]
    - role: monitoring
      tags: [all]
    - role: tailscale
      tags: [all]
    # - role: user
    #   tags: [all]
