---
- name: Configure RaspberryPi OS
  hosts: localhost
  connection: local
  become: true

  roles:
    - role: fde
    - role: main
    - role: monitoring
    - role: ../roles/tailscale
    - role: user
