---
- name: Check if hc-ping uuid has been set
  ansible.builtin.stat:
    path: /root/hc-ping-uuid.txt
  register: hcping_uuid_file

- name: Fetch hc-ping uuid
  ansible.builtin.slurp:
    src: /root/hc-ping-uuid.txt
  when: hcping_uuid_file.stat.exists
  register: hcping_uuid

- name: Create hc-ping service
  when: hcping_uuid_file.stat.exists
  ansible.builtin.template:
    dest: /etc/systemd/system/hc-ping.service
    group: root
    mode: "0644"
    owner: root
    src: hc-ping.service.j2

- name: Create hc-ping timer
  when: hcping_uuid_file.stat.exists
  ansible.builtin.copy:
    dest: /etc/systemd/system/hc-ping.timer
    group: root
    mode: "0644"
    owner: root
    src: hc-ping.timer

- name: Enable hc-ping timer
  when: hcping_uuid_file.stat.exists
  ansible.builtin.systemd:
    enabled: true
    name: hc-ping.timer
    state: started
