---
- name: Adding APT pin for backports packages
  ansible.builtin.template:
    dest: /etc/apt/preferences.d/media
    group: root
    mode: "0644"
    owner: root
    src: media.j2
  register: media_apt_pin

- name: Installing media packages
  ansible.builtin.apt:
    name:
      - cksfv
      - deluge
      - gallery-dl
      - keepassxc
      - sabnzbdplus
      - torbrowser-launcher
      - vlc
      - youtube-dl
      - yt-dlp
    state: present
    update_cache: "{{ media_apt_pin.changed }}"

# https://blogs.gnome.org/thaller/2016/08/26/mac-address-spoofing-in-networkmanager-1-4-0/
- name: Enabling random MAC addresses
  when: mtype == 'media'
  ansible.builtin.copy:
    dest: /etc/NetworkManager/conf.d/30-mac-randomization.conf
    group: root
    mode: "0644"
    owner: root
    src: mac-randomization.conf
  notify:
    - Restart network manager
