---
- name: install media packages
  ansible.builtin.apt:
    name:
      - cksfv
      - deluge
      - gallery-dl
      - keepassxc
      - sabnzbdplus
      - torbrowser-launcher
      - vlc
      - youtube-dl
      - yt-dlp

# https://blogs.gnome.org/thaller/2016/08/26/mac-address-spoofing-in-networkmanager-1-4-0/
- name: enable random mac addresses
  when: mtype == 'media'
  ansible.builtin.copy:
    src: mac-randomization.conf
    owner: root
    group: root
    mode: 0644
    dest: /etc/NetworkManager/conf.d/30-mac-randomization.conf
  notify:
    - restart network manager
