---
- name: install media packages
  ansible.builtin.apt:
    name:
      - cksfv
      - deluge
      - gallery-dl
      - sabnzbdplus
      - torbrowser-launcher
      - vlc
      - youtube-dl
      - yt-dlp
