---
- name: Copying systemd-resolved configuration
  become: true
  ansible.builtin.copy:
    dest: /etc/systemd/resolved.conf
    group: root
    mode: "0644"
    owner: root
    src: resolved.conf

- name: Linking systemd-resolved stub resolver to /etc/resolv.conf
  become: true
  when: mmode != 'setup' # don't run before first reboot
  ansible.builtin.file:
    dest: /etc/resolv.conf
    force: true
    src: /run/systemd/resolve/stub-resolv.conf
    state: link

- name: Enabling systemd-resolved
  become: true
  ansible.builtin.systemd:
    enabled: true
    name: systemd-resolved.service
