---
- name: install resolved configuration
  become: true
  copy:
    dest: /etc/systemd/resolved.conf
    owner: root
    group: root
    mode: 0644
    src: resolved.conf

- name: symlink systemd resolvd stub to /etc/resolv.conf
  become: true
  when: mmode != 'setup' # don't run before first reboot
  file:
    dest: /etc/resolv.conf
    src: /run/systemd/resolve/stub-resolv.conf
    state: link
    force: true

- name: enable systemd-resolved
  become: true
  systemd: name=systemd-resolved.service enabled=yes
