---
- name: Creating systemd-networkd DHCP configuration
  ansible.builtin.copy:
    dest: /etc/systemd/network/10-all-interfaces-dhcp.network
    group: root
    mode: "0644"
    owner: root
    src: dhcp.network
  notify:
    - Restart systemd-networkd

- name: Starting and enabling systemd-networkd
  ansible.builtin.systemd:
    enabled: true
    name: systemd-networkd.service
    state: started

- name: Removing old networking packages
  ansible.builtin.apt:
    name:
      - dhcpcd-base
      - ifupdown
      - netplan.io
      - network-manager
      - resolvconf
    purge: true
    state: absent

- name: Removing old networking configuration
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/network
