---
- name: Restart systemd-resolved
  ansible.builtin.systemd:
    name: systemd-resolved.service
    state: restarted
    daemon_reload: true

- name: Restart systemd-timesyncd
  ansible.builtin.systemd:
    name: systemd-timesyncd.service
    state: restarted
    daemon_reload: true
