---
- name: Restart sshd
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: sshd.service
    state: restarted

- name: Restart ufw
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: ufw.service
    state: restarted
