---
- name: Install wine
  when:
    - multilib == 'true'
    - mtype == 'personal' or mtype == 'media'
  become: true
  community.general.pacman:
    name:
      - wine
      - wine-gecko
      - wine-mono
      - winetricks

- name: Install lib32 libraries
  when:
    - multilib == 'true'
    - mtype == 'personal' or mtype == 'media'
  become: true
  community.general.pacman:
    name:
      - lib32-alsa-plugins
      - lib32-libpulse

- name: Install picard
  when: mtype == 'personal' or mtype == 'media'
  become: true
  community.general.pacman:
    name: picard

- name: Install other music applications
  when: mtype == 'personal' or mtype == 'media'
  kewlfft.aur.aur:
    name:
      - exact-audio-copy
      - foobar2000
      - mp3tag

- name: Install tor browser bundle
  when: mtype == 'personal' or mtype == 'media'
  become: true
  community.general.pacman:
    name: tor-browser

- name: Install google-chrome
  when: mtype != 'server'
  kewlfft.aur.aur:
    name: google-chrome

- name: Install youtube-dl
  when: mtype == 'personal' or mtype == 'media'
  become: true
  community.general.pacman:
    name:
      - youtube-dl
      - yt-dlp

- name: Install gallery-dl
  when: mtype == 'personal' or mtype == 'media'
  become: true
  community.general.pacman:
    name: gallery-dl

- name: Install other media dependencies
  when: mtype == 'personal' or mtype == 'media'
  become: true
  community.general.pacman:
    name:
      - handbrake
      - libaacs
      - libdvdcss
      - vlc

- name: Install torrent client
  when: mtype == 'personal' or mtype == 'media'
  become: true
  community.general.pacman:
    name:
      - cksfv
      - deluge
