---
- name: install wine
  when:
    - multilib == 'true'
    - mtype == 'personal' or mtype == 'media'
  become: true
  pacman:
    name:
      - wine
      - wine-mono
      - wine-gecko
      - winetricks

- name: install lib32 libraries
  when:
    - multilib == 'true'
    - mtype == 'personal' or mtype == 'media'
  become: true
  pacman:
    name:
      - lib32-libpulse
      - lib32-alsa-plugins

- name: install picard
  when: mtype == 'personal' or mtype == 'media'
  become: true
  pacman: name=picard

- name: install other music applications
  when: mtype == 'personal' or mtype == 'media'
  aur:
    name:
      - foobar2000
      - mp3tag

# TODO: switch this to WKD once supported by the module
- name: add tor browser bundle signing key
  when: mtype == 'personal' or mtype == 'media'
  gpg_key:
    fpr: EF6E286DDA85EA2A4BA7DE684E2C6E8793298290

- name: install tor browser bundle
  when: mtype == 'personal' or mtype == 'media'
  aur: name=tor-browser

- name: install google-chrome
  aur: name=google-chrome

- name: install youtube-dl
  when: mtype == 'personal' or mtype == 'media'
  become: true
  pacman:
    name:
      - youtube-dl
      - yt-dlp

- name: install other media dependencies
  when: mtype == 'personal' or mtype == 'media'
  become: true
  pacman:
    name:
      - vlc
      - libdvdcss
      - libaacs
