---
- name: Installing Wine
  when:
    - multilib == 'true'
    - mtype == 'personal' or mtype == 'media'
  become: true
  community.general.pacman:
    name:
      - wine
      - wine-gecko
      - wine-mono
      - winetricks
    state: present

- name: Installing lib32 libraries for Wine
  when:
    - multilib == 'true'
    - mtype == 'personal' or mtype == 'media'
  become: true
  community.general.pacman:
    name:
      - lib32-alsa-plugins
      - lib32-libpulse
    state: present

- name: Installing picard
  when: mtype == 'personal' or mtype == 'media'
  become: true
  community.general.pacman:
    name: picard
    state: present

- name: Installing Wine-based music applications
  when: mtype == 'personal' or mtype == 'media'
  kewlfft.aur.aur:
    name:
      - exact-audio-copy
      - foobar2000
      - mp3tag
    state: present

- name: Installing the Tor Browser bundle
  when: mtype == 'personal' or mtype == 'media'
  become: true
  community.general.pacman:
    name: tor-browser
    state: present

- name: Installing Google Chrome
  when: mtype != 'server'
  kewlfft.aur.aur:
    name: google-chrome
    state: present

- name: Installing yt-dlp
  when: mtype == 'personal' or mtype == 'media'
  become: true
  community.general.pacman:
    name:
      - youtube-dl
      - yt-dlp
    state: present

- name: Installing gallery-dl
  when: mtype == 'personal' or mtype == 'media'
  become: true
  community.general.pacman:
    name: gallery-dl
    state: present

- name: Installing other media applications
  when: mtype == 'personal' or mtype == 'media'
  become: true
  community.general.pacman:
    name:
      - handbrake
      - libaacs
      - libdvdcss
      - vlc
    state: present

- name: Installing a torrent client
  when: mtype == 'personal' or mtype == 'media'
  become: true
  community.general.pacman:
    name:
      - cksfv
      - deluge
    state: present
