---
- name: Installing Wine
  when:
    - multilib == 'true'
    - mtype == 'personal' or mtype == 'media'
  become: true
  community.general.pacman:
    name:
      - wine
      - wine-gecko
      - wine-mono
      - winetricks
    state: present

- name: Installing lib32 libraries for Wine
  when:
    - multilib == 'true'
    - mtype == 'personal' or mtype == 'media'
  become: true
  community.general.pacman:
    name:
      - lib32-alsa-plugins
      - lib32-libpulse
    state: present

- name: Installing picard
  when: mtype == 'personal' or mtype == 'media'
  become: true
  community.general.pacman:
    name: picard
    state: present

- name: Installing Wine-based music applications
  when:
    - multilib == 'true'
    - mtype == 'personal' or mtype == 'media'
  kewlfft.aur.aur:
    name:
      - exact-audio-copy
      - foobar2000
      - mp3tag
    state: present

- name: Installing the Tor Browser bundle
  when: mtype == 'personal' or mtype == 'media'
  become: true
  community.general.pacman:
    name: tor-browser-bin
    state: present

- name: Installing Google Chrome
  kewlfft.aur.aur:
    name: google-chrome
    state: present

- name: Installing yt-dlp
  when: mtype == 'personal' or mtype == 'media'
  become: true
  community.general.pacman:
    name:
      - yt-dlp
    state: present

- name: Installing yt-dlp optional dependencies
  when: mtype == 'personal' or mtype == 'media'
  become: true
  community.general.pacman:
    name:
      - python-brotli
      - python-brotlicffi
      - python-mutagen
      - python-pycryptodomex
      - python-secretstorage
      - python-websockets
      - python-xattr

- name: Installing gallery-dl
  when: mtype == 'personal' or mtype == 'media'
  become: true
  community.general.pacman:
    name: gallery-dl
    state: present

- name: Installing other media applications
  when: mtype == 'personal' or mtype == 'media'
  become: true
  community.general.pacman:
    name:
      - handbrake
      - libaacs
      - libdvdcss
      - vlc
    state: present

- name: Installing a torrent client
  when: mtype == 'personal' or mtype == 'media'
  become: true
  community.general.pacman:
    name:
      - cksfv
      - deluge
    state: present

# TODO: this lives here because it depends on wine, but it (and wine) should
#       go someplace else
- name: Installing winbox
  when:
    - multilib == 'true'
    - mtype == 'personal'
  kewlfft.aur.aur:
    name: winbox
    state: present
