#!/bin/bash -e

echo "mfinelli ALL=(ALL:ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/mfinelli
sudo chmod 0400 /etc/sudoers.d/mfinelli

sudo apt update && sudo apt upgrade -y
sudo apt install -y ansible git

wdir="$(mktemp -d)"
sdir="$(pwd)"
cd "$wdir"

git clone https://github.com/mfinelli/arch-install.git
cd arch-install/ubuntu

sudo ansible-playbook ubuntu.yml

cd "$sdir"
rm -rf "$wdir"

exit 0
