#!/bin/bash -e

# sudo add-apt-repository ppa:mfinelli/supermario
sudo apt update && sudo apt upgrade -y
sudo apt install -y ansible git

wdir="$(mktemp -d)"
sdir="$(pwd)"
cd "$wdir"

git clone https://github.com/mfinelli/arch-install.git
cd arch-install/ubuntu

./run.bash

cd "$sdir"
rm -rf "$wdir"

exit 0
