---
- hosts: localhost
  tasks:
    - name: add supermario ppa
      ansible.builtin.apt_repository: repo=ppa:mfinelli/supermario

    - name: ensure manual dependencies
      ansible.builtin.apt:
        name:
          - ansible
          - curl
          - git
        update_cache: yes

    - name: install other dependencies
      ansible.builtin.apt:
        name:
          - docker-compose
          - docker.io
          - fd-find
          - font-manager
          - fzf
          - golang
          - htop
          - jq
          - libarchive-tools
          - pcscd
          - pwgen
          - ripgrep
          - rust-all
          - scdaemon
          - shellcheck
          - silversearcher-ag
          - tmux
          - universal-ctags
          - urlwatch
          - vim
          - whois
          - zsh
          - zsh-autosuggestions
          - zsh-syntax-highlighting

    - name: install other software
      ansible.builtin.apt:
        name:
          - gnome-tweaks
          - git-crypt
          - default-jre-headless
          - kubectx

    - name: install packaging dependencies
      ansible.builtin.apt:
        name:
          - apt-file
          - bzr-builddeb
          - dh-make
          - pbuilder
          - ubuntu-dev-tools

    - name: install keymapper dependencies
      ansible.builtin.apt:
        name:
          - cmake
          - libudev-dev
          - libusb-1.0-0-dev
          - libx11-dev

# vim: ft=yaml.ansible
