---
- hosts: localhost
  connection: local
  become: true

  roles:
    - role: base
    - role: chrome
      when: mtype != 'server'
    - role: desktop
      when: mtype != 'server'
    - role: dropbox
      when: mtype == 'gaming'
    - role: gaming
      when: mtype == 'gaming'
    - role: media
      when: mtype != 'server'
    - role: mega
      when: mtype != 'server'
    - role: onepassword
      when: mtype != 'server'
    - role: server
      when: mtype == 'server'
    - role: tailscale

  tasks:
    # mullvad doesn't seem to have an apt repository right now, so I'm keeping
    # this here to make it easier to update
    # https://github.com/mullvad/mullvadvpn-app/issues/3049
    - name: install mullvad vpn
      when: mtype != 'server'
      ansible.builtin.apt: deb=https://mullvad.net/media/app/MullvadVPN-2023.1_amd64.deb
