---
- hosts: localhost
  tasks:
    - name: add supermario ppa
      ansible.builtin.apt_repository: repo=ppa:mfinelli/supermario

    - name: ensure manual dependencies
      ansible.builtin.apt:
        name:
          - ansible
          - curl
          - git
        update_cache: yes

    - name: install other dependencies
      ansible.builtin.apt:
        name:
          - awscli
          - borgbackup
          - cksfv
          - deluge
          - docker-compose
          - docker.io
          - fd-find
          - font-manager
          - fonts-firacode
          - fonts-powerline
          - fzf
          - gnome-tweaks
          - htop
          - jq
          - libarchive-tools
          - moreutils
          - p7zip-full
          - p7zip-rar
          - pass
          - pass-extension-otp
          - pcscd
          - pv
          - pwgen
          - rclone
          - ripgrep
          - sabnzbdplus
          - scdaemon
          - silversearcher-ag
          - thefuck
          - tmux
          - universal-ctags
          - urlwatch
          - vim
          - vlc
          - whois
          - youtube-dl
          - zoxide


# vim: ft=yaml.ansible
