---
- name: Configuring Ubuntu system
  hosts: localhost
  connection: local
  become: true

  roles:
    - role: base
    - role: chrome
      when: mtype != 'server'
    - role: desktop
      when: mtype != 'server'
    - role: dropbox
      when: mtype == 'gaming'
    - role: firefox
      when: mtype != 'server'
    - role: gaming
      when: mtype == 'gaming'
    - role: media
      when: mtype != 'server'
    - role: mega
      when: mtype != 'server'
    - role: mullvadvpn
      when: mtype != 'server'
    - role: onepassword
      when: mtype != 'server'
    - role: server
      when: mtype == 'server'
    - role: tailscale

  tasks:
    # discord doesn't have an apt repository (and doesn't seem to be on the
    # roadmap at all, so this is the best we can do for now)
    - name: Installing Discord
      when: mtype != 'server'
      ansible.builtin.apt:
        # curl -sI \
        #   'https://discord.com/api/download?platform=linux&format=deb' | \
        # grep -i location
        deb: https://dl.discordapp.net/apps/linux/0.0.68/discord-0.0.68.deb
