---
- name: install unbound and dependencies
  become: true
  community.general.pacman:
    name:
      - unbound
      - expat
      - openresolv

- name: download initial root hints
  become: true
  ansible.builtin.get_url:
    url: https://www.internic.net/domain/named.cache
    dest: /etc/unbound/root.hints
    mode: 0644
    owner: root
    group: root

- name: copy resolveconf.conf
  become: true
  ansible.builtin.copy:
    src: resolvconf.conf
    dest: /etc/resolvconf.conf
    mode: 0644
    owner: root
    group: root

- name: Run resolvconf -u
  become: true
  ansible.builtin.command: resolvconf -u
  register: resolvconf_updated
  changed_when: resolvconf_updated.rc == 0
  failed_when: resolvconf_updated.rc != 0

- name: Install unbound configuration
  become: true
  ansible.builtin.copy:
    src: unbound.conf
    dest: /etc/unbound/unbound.conf
    mode: 0644
    owner: root
    group: root

- name: Install root-hints service
  become: true
  ansible.builtin.copy:
    src: root-hints.service
    dest: /etc/systemd/system/root-hints.service
    mode: 0644
    owner: root
    group: root

- name: Install root-hints timer
  become: true
  ansible.builtin.copy:
    src: root-hints.timer
    dest: /etc/systemd/system/root-hints.timer
    mode: 0644
    owner: root
    group: root

- name: Install network manager resolveconf manager config
  when: mtype != 'server'
  become: true
  ansible.builtin.copy:
    src: rc-manager.conf
    dest: /etc/NetworkManager/conf.d/rc-manager.conf
    mode: 0644
    owner: root
    group: root

- name: enable root-hints timer
  become: true
  ansible.builtin.systemd: name=root-hints.timer enabled=true

- name: enable unbound
  become: true
  ansible.builtin.systemd: name=unbound.service enabled=true
