---
- name: Installing unbound and dependencies
  become: true
  community.general.pacman:
    name:
      - expat
      - openresolv
      - unbound

- name: Downloading initial root hints
  become: true
  ansible.builtin.get_url:
    dest: /etc/unbound/root.hints
    group: root
    mode: "0644"
    owner: root
    url: https://www.internic.net/domain/named.cache

- name: Copying "/etc/resolveconf.conf"
  become: true
  ansible.builtin.copy:
    dest: /etc/resolvconf.conf
    group: root
    mode: "0644"
    owner: root
    src: resolvconf.conf

- name: Running `resolvconf -u`
  become: true
  ansible.builtin.command: resolvconf -u
  register: resolvconf_updated
  changed_when: resolvconf_updated.rc == 0
  failed_when: resolvconf_updated.rc != 0

- name: Copying unbound configuration
  become: true
  ansible.builtin.copy:
    dest: /etc/unbound/unbound.conf
    group: root
    mode: "0644"
    owner: root
    src: unbound.conf

- name: Installing root-hints service
  become: true
  ansible.builtin.copy:
    dest: /etc/systemd/system/root-hints.service
    group: root
    mode: "0644"
    owner: root
    src: root-hints.service

- name: Installing root-hints timer
  become: true
  ansible.builtin.copy:
    dest: /etc/systemd/system/root-hints.timer
    group: root
    mode: "0644"
    owner: root
    src: root-hints.timer

- name: Copying Network Manager resolvconf manager configuration
  become: true
  ansible.builtin.copy:
    dest: /etc/NetworkManager/conf.d/rc-manager.conf
    group: root
    mode: "0644"
    owner: root
    src: rc-manager.conf

- name: Enabling root-hints timer
  become: true
  ansible.builtin.systemd:
    enabled: true
    name: root-hints.timer

- name: Enabling unbound service
  become: true
  ansible.builtin.systemd:
    enabled: true
    name: unbound.service
