---
- name: Install server packages
  ansible.builtin.apt:
    name:
      - screen

- name: Ensure mario user
  ansible.builtin.user:
    name: mario
    shell: /bin/bash

- name: Add cloud dev ssh key
  ansible.posix.authorized_key:
    exclusive: true
    key: |
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII4kUwwZEPUHbx17N3VOVXPmQoRF9u+gkWj2nnvtYt2h mario
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOy1DGNkaHw4UiGX8H7L4ruWjWBYFSkOEvB1jqAt5rdz mario@iphone
    user: mario

- name: Ensure mario sudo rule
  ansible.builtin.copy:
    dest: /etc/sudoers.d/mario
    group: root
    mode: "0440"
    owner: root
    src: mario.sudoer
    validate: visudo -cf %s
