---
- name: Installing screen
  ansible.builtin.apt:
    name:
      - screen
    state: present

- name: Creating the "mario" user
  ansible.builtin.user:
    name: mario
    shell: /bin/bash
    state: present

- name: Configuring SSH keys for "mario"
  ansible.posix.authorized_key:
    exclusive: true
    # yamllint disable rule:line-length
    key: |
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII4kUwwZEPUHbx17N3VOVXPmQoRF9u+gkWj2nnvtYt2h mario
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOy1DGNkaHw4UiGX8H7L4ruWjWBYFSkOEvB1jqAt5rdz mario@iphone
    # yamllint enable rule:line-length
    state: present
    user: mario

- name: Adding sudo rule for "mario"
  ansible.builtin.copy:
    dest: /etc/sudoers.d/mario
    group: root
    mode: "0440"
    owner: root
    src: mario.sudoer
    validate: visudo -cf %s
