---
- name: download tailscale signing key
  ansible.builtin.get_url:
    url: https://pkgs.tailscale.com/stable/ubuntu/{{ ansible_distribution_release }}.noarmor.gpg
    dest: /usr/share/keyrings/tailscale-archive-keyring.gpg
    owner: root
    group: root
    mode: 0644

- name: add tailscale signing key
  ansible.builtin.apt_key:
    url: https://pkgs.tailscale.com/stable/ubuntu/{{ ansible_distribution_release }}.gpg

- name: add tailscale repository
  ansible.builtin.apt_repository:
    repo: >
      deb [signed-by=/usr/share/keyrings/tailscale-archive-keyring.gpg]
      https://pkgs.tailscale.com/stable/ubuntu {{ ansible_distribution_release }} main
    filename: tailscale

- name: install tailscale
  ansible.builtin.apt: name=tailscale update_cache=yes
