---
- hosts: localhost
  tasks:
    - name: get user's primary group
      ansible.builtin.command: id -gn {{ ansible_user_id }}
      register: whoami_group
      changed_when: false

    - name: install python packages
      ansible.builtin.pip:
        name:
          - azure-identity
          - azure-mgmt-compute
          - azure-mgmt-network
          - azure-storage-blob
        executable: /usr/local/bin/pip3

    - name: install helm plugins
      kubernetes.core.helm_plugin:
        plugin_path: "{{ item }}"
      loop:
        - https://github.com/databus23/helm-diff.git
        - https://github.com/jkroepke/helm-secrets.git

    - name: ensure local bin directory
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/bin"
        owner: "{{ ansible_user_id }}"
        group: "{{ whoami_group.stdout }}"
        mode: 0755
        state: directory

    - name: install pluto
      ansible.builtin.unarchive:
        src: https://github.com/FairwindsOps/pluto/releases/download/v4.0.5/pluto_4.0.5_darwin_amd64.tar.gz
        dest: "{{ ansible_user_dir }}/bin"
        remote_src: true

    - name: cleanup extra pluto files
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/bin/{{ item }}"
        state: absent
      loop:
        - LICENSE
        - README.md

    - name: create docker plugins directory
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/{{ item }}"
        owner: "{{ ansible_user_id }}"
        group: "{{ whoami_group.stdout }}"
        mode: 0755
        state: directory
      loop:
        - .docker
        - .docker/cli-plugins

    - name: symlink docker-compose plugin
      ansible.builtin.file:
        src: /usr/local/opt/docker-compose/bin/docker-compose
        dest: "{{ ansible_user_dir }}/.docker/cli-plugins/docker-compose"
        state: link
