---
- name: Configure macOS
  hosts: localhost
  tasks:
    - name: Get user's primary group
      ansible.builtin.command: id -gn {{ ansible_user_id }}
      register: whoami_group
      changed_when: false

    - name: Install python packages
      ansible.builtin.pip:
        name:
          - azure-identity
          - azure-mgmt-compute
          - azure-mgmt-network
          - azure-storage-blob
        executable: /usr/local/bin/pip3

    - name: Install helm plugins
      kubernetes.core.helm_plugin:
        plugin_path: "{{ item }}"
      loop:
        - https://github.com/databus23/helm-diff.git
        - https://github.com/jkroepke/helm-secrets.git

    - name: Ensure local bin directory
      ansible.builtin.file:
        group: "{{ whoami_group.stdout }}"
        mode: "0755"
        owner: "{{ ansible_user_id }}"
        path: "{{ ansible_user_dir }}/bin"
        state: directory

    - name: Install pluto
      ansible.builtin.unarchive:
        dest: "{{ ansible_user_dir }}/bin"
        remote_src: true
        src: "https://github.com/FairwindsOps/pluto/releases/download/\
          v5.15.1/pluto_5.15.1_darwin_amd64.tar.gz"

    - name: Cleanup extra pluto files
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/bin/{{ item }}"
        state: absent
      loop:
        - LICENSE
        - README.md

    - name: Create docker plugins directory
      ansible.builtin.file:
        group: "{{ whoami_group.stdout }}"
        mode: "0755"
        owner: "{{ ansible_user_id }}"
        path: "{{ ansible_user_dir }}/{{ item }}"
        state: directory
      loop:
        - .docker
        - .docker/cli-plugins

    - name: Symlink docker-compose plugin
      ansible.builtin.file:
        dest: "{{ ansible_user_dir }}/.docker/cli-plugins/docker-compose"
        src: /usr/local/opt/docker-compose/bin/docker-compose
        state: link
