---
- name: Downloading the 1Password signing key
  ansible.builtin.get_url:
    dest: /etc/apt/keyrings/1password-archive-keyring.asc
    group: root
    mode: "0644"
    owner: root
    url: https://downloads.1password.com/linux/keys/1password.asc
  register: onepassword_repository_key

- name: Adding the 1Password signing key
  ansible.builtin.command:
    cmd: >-
      gpg --dearmor -o /usr/share/keyrings/1password-archive-keyring.gpg
      /etc/apt/keyrings/1password-archive-keyring.asc
    creates: "{{ onepassword_repository_key.changed | ternary('',
      '/usr/share/keyrings/1password-archive-keyring.gpg') | default(omit,
      true) }}"

- name: Adding the 1Password repository
  ansible.builtin.template:
    dest: /etc/apt/sources.list.d/1password.sources
    group: root
    mode: "0644"
    owner: root
    src: 1password.sources.j2
  register: onepassword_repository

- name: Creating the debsig-verify directories
  ansible.builtin.file:
    group: root
    mode: "0755"
    owner: root
    path: "{{ item }}"
    state: directory
  loop:
    - /etc/debsig/policies/AC2D62742012EA22
    - /usr/share/debsig/keyrings/AC2D62742012EA22

- name: Downloading the debsig-verify policy
  ansible.builtin.get_url:
    dest: /etc/debsig/policies/AC2D62742012EA22/1password.pol
    group: root
    mode: "0644"
    owner: root
    url: https://downloads.1password.com/linux/debian/debsig/1password.pol

- name: Adding the debsig-verify policy
  ansible.builtin.command:
    cmd: >
      gpg --dearmor --output
      /usr/share/debsig/keyrings/AC2D62742012EA22/debsig.gpg
      /usr/share/keyrings/1password-archive-keyring.gpg
    creates: /usr/share/debsig/keyrings/AC2D62742012EA22/debsig.gpg

- name: Installing 1Password
  ansible.builtin.apt:
    name: 1password
    state: present
    update_cache: "{{ onepassword_repository.changed }}"
