---
- name: Adding the 1Password signing key
  ansible.builtin.apt_key:
    keyring: /usr/share/keyrings/1password-archive-keyring.gpg
    state: present
    url: https://downloads.1password.com/linux/keys/1password.asc

- name: Adding the 1Password repository
  ansible.builtin.apt_repository:
    filename: 1password
    repo: >
      deb [arch=amd64
      signed-by=/usr/share/keyrings/1password-archive-keyring.gpg]
      https://downloads.1password.com/linux/debian/amd64 stable main
    update_cache: true

- name: Creating the debsig-verify directories
  ansible.builtin.file:
    group: root
    mode: "0755"
    owner: root
    path: "{{ item }}"
    state: directory
  loop:
    - /etc/debsig/policies/AC2D62742012EA22
    - /usr/share/debsig/keyrings/AC2D62742012EA22

- name: Downloading the debsig-verify policy
  ansible.builtin.get_url:
    dest: /etc/debsig/policies/AC2D62742012EA22/1password.pol
    group: root
    mode: "0644"
    owner: root
    url: https://downloads.1password.com/linux/debian/debsig/1password.pol

- name: Adding the debsig-verify policy
  ansible.builtin.command:
    cmd: >
      gpg --dearmor --output
      /usr/share/debsig/keyrings/AC2D62742012EA22/debsig.gpg
      /usr/share/keyrings/1password-archive-keyring.gpg
    creates: /usr/share/debsig/keyrings/AC2D62742012EA22/debsig.gpg

- name: Installing 1Password
  ansible.builtin.apt:
    name: 1password
    state: present
