---
- name: Creating systemd unit drop-in folder
  become: true
  ansible.builtin.file:
    group: root
    mode: "0755"
    owner: root
    path: /etc/systemd/system/vector.service.d
    state: directory

- name: Installing hardening drop-in
  become: true
  ansible.builtin.copy:
    dest: /etc/systemd/system/vector.service.d/hardening.conf
    owner: root
    group: root
    mode: "0644"
    src: vector.service
  notify:
    - Restart vector

- name: Installing vector on Archlinux
  when: ansible_facts["os_family"] == "Archlinux"
  ansible.builtin.include_tasks: install-arch.yml

- name: Installing vector on Debian-based systems
  when: ansible_facts["os_family"] == "Debian"
  ansible.builtin.include_tasks: install-debian.yml

- name: Checking if the Vector secret has been set
  ansible.builtin.stat:
    path: /root/vector-secret.txt
  register: monitoring_vector_secret_file

- name: Fetching the Vector secret
  ansible.builtin.slurp:
    path: /root/vector-secret.txt
  when: monitoring_vector_secret_file.stat.exists
  register: monitoring_vector_secret

- name: Setting permissions for Vector secret
  ansible.builtin.file:
    group: root
    mode: "0400"
    owner: root
    path: /root/vector-secret.txt
    state: file
  when: monitoring_vector_secret_file.stat.exists

- name: Copying main Vector configuration
  become: true
  ansible.builtin.template:
    dest: /etc/vector/config.yaml
    owner: vector
    group: vector
    mode: "0400"
    src: vector.yml.j2
  notify:
    - Restart vector

- name: Starting and enabling vector
  become: true
  ansible.builtin.systemd:
    enabled: "{{ monitoring_vector_secret_file.stat.exists }}"
    name: vector.service
    state: "{{ 'started' if monitoring_vector_secret_file.stat.exists
      else 'stopped' }}"
