---
- name: restart systemd-resolved
  systemd: name=systemd-resolved state=restarted daemon_reload=yes

- name: restart NetworkManager
  systemd: name=NetworkManager state=restarted daemon_reload=yes
