---
- name: Restart systemd-resolved
  ansible.builtin.systemd:
    daemon_reload: true
    name: systemd-resolved
    state: restarted

- name: Restart NetworkManager
  ansible.builtin.systemd:
    daemon_reload: true
    name: NetworkManager
    state: restarted
