---
- name: restart systemd-resolved
  ansible.builtin.systemd: name=systemd-resolved state=restarted daemon_reload=yes

- name: restart NetworkManager
  ansible.builtin.systemd: name=NetworkManager state=restarted daemon_reload=yes
