---
- name: Ensure resolved.conf.d directory
  ansible.builtin.file:
    group: root
    mode: "0755"
    owner: root
    path: /etc/systemd/resolved.conf.d
    state: directory

- name: Copy custom systemd-resolved configuration
  ansible.builtin.copy:
    dest: /etc/systemd/resolved.conf.d/dns.conf
    group: root
    mode: "0644"
    owner: root
    src: resolved.conf
  notify:
    - Restart systemd-resolved

- name: Ensure manual dependencies
  ansible.builtin.apt:
    name:
      - ansible
      - curl
      - git
    update_cache: true

- name: Uninstall apt https transport
  ansible.builtin.apt:
    name: apt-transport-https
    state: absent

- name: Add supermario ppa
  ansible.builtin.template:
    dest: /etc/apt/sources.list.d/supermario.list
    group: root
    mode: "0644"
    owner: root
    src: supermario.list.j2

- name: Install new sources list
  when: mtype != 'server'
  ansible.builtin.template:
    dest: /etc/apt/sources.list
    group: root
    mode: "0664"
    owner: root
    src: sources.list.j2

- name: Install base packages
  ansible.builtin.apt:
    name:
      - fd-find
      - fzf
      - htop
      - jq
      - libarchive-tools
      - moreutils
      - neofetch
      - pv
      - pwgen
      - ripgrep
      - silversearcher-ag
      - thefuck
      - universal-ctags
      - urlwatch
      - vim
      - whois
    update_cache: true

# https://askubuntu.com/a/1246984
- name: Never install phased updates
  ansible.builtin.copy:
    dest: /etc/apt/apt.conf.d/99-Phased-Updates
    group: root
    mode: "0644"
    owner: root
    src: phased-updates

- name: Uninstall ubuntu reporting programs
  ansible.builtin.apt:
    name:
      - apport
      - ubuntu-report
      - whoopsie
    state: absent
