---
- name: Creating systemd configuration directories
  ansible.builtin.file:
    group: root
    mode: "0755"
    owner: root
    path: /etc/systemd/{{ item }}.conf.d
    state: directory
  loop:
    - resolved
    - timesyncd

- name: Copying custom systemd-resolved configuration
  ansible.builtin.copy:
    dest: /etc/systemd/resolved.conf.d/dns.conf
    group: root
    mode: "0644"
    owner: root
    src: resolved.conf
  notify:
    - Restart systemd-resolved

- name: Flushing handlers
  ansible.builtin.meta: flush_handlers

- name: Copying custom systemd-timesyncd configuration
  ansible.builtin.copy:
    dest: /etc/systemd/timesyncd.conf.d/time.conf
    group: root
    mode: "0644"
    owner: root
    src: timesyncd.conf
  notify:
    - Restart systemd-timesyncd

- name: Installing manually installed packages
  ansible.builtin.apt:
    name:
      - ansible
      - curl
      - git
    state: present
    update_cache: true

- name: Installing ansible dependencies
  ansible.builtin.apt:
    name:
      - python3-apt
    state: present

- name: Downloading "supermario" PPA signing key
  ansible.builtin.get_url:
    dest: /etc/apt/keyrings/supermario-archive-keyring.asc
    group: root
    mode: "0644"
    owner: root
    url: "https://keyserver.ubuntu.com/pks/lookup?op=get&search=\
      0x0f6e5a38709dbd497ceb4eccc80124bb8ab9cff9"
  register: base_supermario_key

- name: Adding "supermario" PPA signing key
  ansible.builtin.command:
    cmd: >-
      gpg --dearmor -o /usr/share/keyrings/supermario-archive-keyring.gpg
      /etc/apt/keyrings/supermario-archive-keyring.asc
    creates: "{{ base_supermario_key.changed | ternary('',
      '/usr/share/keyrings/google-archive-keyring.gpg') | default(omit,
      true) }}"

- name: Adding "supermario" PPA
  ansible.builtin.template:
    dest: /etc/apt/sources.list.d/supermario.sources
    group: root
    mode: "0644"
    owner: root
    src: supermario.sources.j2
  register: base_supermario_ppa

- name: Copying HTTPS-enabled sources.list
  when: mtype != 'server'
  ansible.builtin.template:
    dest: /etc/apt/sources.list.d/ubuntu.sources
    group: root
    mode: "0664"
    owner: root
    src: ubuntu.sources.j2
  register: base_sources

- name: Installing base packages
  ansible.builtin.apt:
    name:
      - bat
      - exfatprogs
      # - fastfetch # TODO: ubuntu 26.04
      - fd-find
      - fzf
      - htop
      - jq
      - libarchive-tools
      - miller
      - moreutils
      - neofetch # TODO: remove in ubuntu 26.04
      - nnn
      - pv
      - pwgen
      - ripgrep
      - silversearcher-ag
      - thefuck
      - universal-ctags
      - urlwatch
      - vim
      - whois
    state: present
    update_cache: "{{ base_supermario_ppa.changed or base_sources.changed }}"

# https://askubuntu.com/a/1246984
- name: Disabling phased updates
  ansible.builtin.copy:
    dest: /etc/apt/apt.conf.d/99-Phased-Updates
    group: root
    mode: "0644"
    owner: root
    src: phased-updates

- name: Uninstalling ubuntu reporting programs
  ansible.builtin.apt:
    name:
      - apport
      - ubuntu-report
      - whoopsie
    state: absent

- name: Enabling simple stateful firewall
  ansible.builtin.include_tasks: firewall.yml
