---
- name: Creating systemd-resolved configuration directory
  ansible.builtin.file:
    group: root
    mode: "0755"
    owner: root
    path: /etc/systemd/resolved.conf.d
    state: directory

- name: Copying custom systemd-resolved configuration
  ansible.builtin.copy:
    dest: /etc/systemd/resolved.conf.d/dns.conf
    group: root
    mode: "0644"
    owner: root
    src: resolved.conf
  notify:
    - Restart systemd-resolved

- name: Installing manually installed packages
  ansible.builtin.apt:
    name:
      - ansible
      - curl
      - git
    state: present
    update_cache: true

- name: Installing ansible dependencies
  ansible.builtin.apt:
    name:
      - python3-apt
    state: present

- name: Uninstalling apt-transport-https
  ansible.builtin.apt:
    name: apt-transport-https
    state: absent

- name: Adding "supermario" PPA
  ansible.builtin.template:
    dest: /etc/apt/sources.list.d/supermario.list
    group: root
    mode: "0644"
    owner: root
    src: supermario.list.j2
  register: base_supermario_ppa

- name: Copying HTTPS-enabled sources.list
  when: mtype != 'server'
  ansible.builtin.template:
    dest: /etc/apt/sources.list
    group: root
    mode: "0664"
    owner: root
    src: sources.list.j2
  register: base_sources

- name: Installing base packages
  ansible.builtin.apt:
    name:
      - bat
      - fd-find
      - fzf
      - htop
      - jq
      - libarchive-tools
      - miller
      - moreutils
      - neofetch
      - nnn
      - pv
      - pwgen
      - ripgrep
      - silversearcher-ag
      - thefuck
      - universal-ctags
      - urlwatch
      - vim
      - whois
    state: present
    update_cache: "{{ base_supermario_ppa.changed or base_sources.changed }}"

# https://askubuntu.com/a/1246984
- name: Disabling phased updates
  ansible.builtin.copy:
    dest: /etc/apt/apt.conf.d/99-Phased-Updates
    group: root
    mode: "0644"
    owner: root
    src: phased-updates

- name: Uninstalling ubuntu reporting programs
  ansible.builtin.apt:
    name:
      - apport
      - ubuntu-report
      - whoopsie
    state: absent

- name: Enabling simple stateful firewall
  ansible.builtin.include_tasks: firewall.yml
