---
# - name: add supermario ppa
#   ansible.builtin.apt_repository: repo=ppa:mfinelli/supermario

- name: ensure resolved.conf.d directory
  ansible.builtin.file:
    path: /etc/systemd/resolved.conf.d
    owner: root
    group: root
    mode: 0755
    state: directory

- name: copy custom systemd-resolved configuration
  ansible.builtin.copy:
    src: resolved.conf
    dest: /etc/systemd/resolved.conf.d/dns.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart systemd-resolved

- name: ensure manual dependencies
  ansible.builtin.apt:
    name:
      - ansible
      - curl
      - git
    update_cache: yes

- name: install apt https transport
  ansible.builtin.apt: name=apt-transport-https

- name: install new sources list
  ansible.builtin.template:
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: 0664
    src: sources.list.j2

- name: install main packages
  ansible.builtin.apt:
    name:
      - caffeine
      - docker-compose
      - docker.io
      - fd-find
      - fonts-firacode
      - fonts-powerline
      - fzf
      - gnome-shell-extensions
      - htop
      - jq
      - libarchive-tools
      - moreutils
      - pv
      - pwgen
      - ripgrep
      - silversearcher-ag
      - thefuck
      - tmux
      - universal-ctags
      - urlwatch
      - vim
      - whois
      - zoxide
    update_cache: yes

- name: disable docker from startup
  ansible.builtin.systemd: name=docker.service enabled=no

- name: install yubikey dependencies
  ansible.builtin.apt:
    name:
      - pcscd
      - scdaemon

- name: install backup programs
  ansible.builtin.apt:
    name:
      - awscli
      - borgbackup
      - p7zip-full
      - p7zip-rar
      - pass
      - pass-extension-otp
      - rclone

- name: install gdm dconf greeter
  ansible.builtin.copy:
    dest: /etc/gdm3/greeter.dconf-defaults
    owner: root
    group: root
    mode: 0644
    src: greeter.dconf-defaults
