---
# - name: add supermario ppa
#   ansible.builtin.apt_repository: repo=ppa:mfinelli/supermario

- name: ensure manual dependencies
  ansible.builtin.apt:
    name:
      - ansible
      - curl
      - git
    update_cache: yes

- name: install apt https transport
  ansible.builtin.apt: name=apt-transport-https

- name: install main packages
  ansible.builtin.apt:
    name:
      - docker-compose
      - docker.io
      - fd-find
      - fonts-firacode
      - fonts-powerline
      - fzf
      - htop
      - jq
      - libarchive-tools
      - moreutils
      - pv
      - pwgen
      - ripgrep
      - silversearcher-ag
      - thefuck
      - tmux
      - universal-ctags
      - urlwatch
      - vim
      - whois
      - zoxide

- name: install yubikey dependencies
  ansible.builtin.apt:
    name:
      - pcscd
      - scdaemon

- name: install backup programs
  ansible.builtin.apt:
    name:
      - awscli
      - borgbackup
      - p7zip-full
      - p7zip-rar
      - pass
      - pass-extension-otp
      - rclone

- name: install gdm dconf greeter
  ansible.builtin.copy:
    dest: /etc/gdm3/greeter.dconf-defaults
    owner: root
    group: root
    mode: 0644
    src: greeter.dconf-defaults
