---
- name: install mariadb
  when: mtype == 'personal'
  become: true
  community.general.pacman: name=mariadb
  register: mariadb_installed

- name: run mysql_install_db
  ansible.builtin.command: mysql_install_db --user=mysql --basedir=/usr --datadir=/var/lib/mysql
  become: true
  when: mariadb_installed.changed

- name: install postgresql
  when: mtype == 'personal'
  become: true
  community.general.pacman: name=postgresql
  register: postgresql_installed

- name: run postgres initdb
  ansible.builtin.command: initdb --locale en_US.utf8 -E UTF8 -D /var/lib/postgres/data
  become: true
  become_user: postgres
  when: postgresql_installed.changed

- name: install redis
  when: mtype == 'personal'
  become: true
  community.general.pacman: name=redis

- name: install redli
  when: mtype == 'personal'
  become: true
  community.general.pacman: name=redli
