---
- name: Installing plymouth and themes
  ansible.builtin.apt:
    name:
      - plymouth
      - plymouth-theme-debian-logo
      - plymouth-themes
    state: present

- name: Updating grub configuration
  ansible.builtin.copy:
    dest: /etc/default/grub
    group: root
    mode: "0644"
    owner: root
    src: grub
  notify:
    - Run update-grub2

- name: Installing plymouth configuration
  ansible.builtin.copy:
    dest: /etc/plymouth/plymouthd.conf
    group: root
    mode: "0644"
    owner: root
    src: plymouthd.conf
  notify:
    - Rebuild initramfs with plymouth

- name: Flushing handlers
  ansible.builtin.meta: flush_handlers

- name: Installing fwupd
  ansible.builtin.apt:
    name: fwupd-signed
    state: present

- name: Installing desktop packages
  ansible.builtin.apt:
    name:
      - caffeine
      - fonts-firacode
      - fonts-firamono-nerd-font
      - fonts-powerline
      - fonts-ubuntu
      - gnome-shell-extension-manager
      - gnome-shell-extensions
      - headsetcontrol
      - houmain-keymapper
      - piper
      - thunderbird
    state: present

- name: Installing desktop CLI software
  ansible.builtin.apt:
    name:
      - du-dust
      - podman
      - podman-docker
      - tmux
      - trash-cli
      - vivid
      - zoxide
    state: present

- name: Installing GNOME extensions
  ansible.builtin.apt:
    name:
      - gnome-shell-extension-appindicator
      - gnome-shell-extension-arc-menu
      - gnome-shell-extension-blur-my-shell
      - gnome-shell-extension-caffeine
      - gnome-shell-extension-dashtodock
      - gnome-shell-extension-debian-updates-indicator
      - gnome-shell-extension-freon
      - gnome-shell-extension-gamemode
      - gnome-shell-extension-nightthemeswitcher
      - gnome-shell-extension-pano
      - gnome-shell-extension-randomwallpaper
      - gnome-shell-extension-weather
      - gnome-shell-extensions-extra

- name: Installing yubikey dependencies
  ansible.builtin.apt:
    name:
      - pcscd
      - scdaemon
    state: present

- name: Installing backup programs
  ansible.builtin.apt:
    name:
      - age
      - awscli
      - borgbackup
      - 7zip
      - 7zip-rar
      - 7zip-standalone
      - pass
      - pass-otp
      - rclone
    state: present

- name: Installing opensnitch
  ansible.builtin.apt:
    name:
      - opensnitch
      - opensnitch-ebpf-modules
      - python3-opensnitch-ui
