---
- name: Installing fwupd
  ansible.builtin.apt:
    name: fwupd-signed
    state: present

- name: Installing desktop packages
  ansible.builtin.apt:
    name:
      - caffeine
      - fonts-firacode
      - fonts-powerline
      - gnome-shell-extension-manager
      - gnome-shell-extensions
    state: present

- name: Installing desktop CLI software
  ansible.builtin.apt:
    name:
      - podman
      - podman-docker
      - tmux
      - vivid
      - zoxide
    state: present

- name: Installing GNOME extensions
  ansible.builtin.apt:
    name:
      - gnome-shell-extension-appindicator
      - gnome-shell-extension-arc-menu
      - gnome-shell-extension-bluetooth-quick-connect
      - gnome-shell-extension-caffeine
      - gnome-shell-extension-dashtodock
      - gnome-shell-extension-freon
      - gnome-shell-extension-gamemode
      - gnome-shell-extension-weather
      - gnome-shell-extensions-extra

- name: Installing yubikey dependencies
  ansible.builtin.apt:
    name:
      - pcscd
      - scdaemon
    state: present

- name: Installing backup programs
  ansible.builtin.apt:
    name:
      - awscli
      - borgbackup
      - p7zip-full
      - p7zip-rar
      - pass
      - pass-otp
      - rclone
    state: present
