---
- name: Configuring Debian system
  hosts: localhost
  connection: local
  become: true

  roles:
    - role: base
    - role: chrome
    # - role: cloudflarewarp
    - role: desktop
    # - role: dropbox
    - role: firefox
    - role: gaming
    - role: media
    - role: mega
    - role: mullvadvpn
    - role: onepassword
    - role: tailscale
    - role: waydroid

  tasks:
    - name: Installing Discord
      ansible.builtin.apt:
        # curl -sI \
        #   'https://discord.com/api/download?platform=linux&format=deb' | \
        # grep -i location
        deb: https://dl.discordapp.net/apps/linux/0.0.111/discord-0.0.111.deb

    # TODO: this will be in forky
    - name: Installing OpenRGB
      ansible.builtin.apt:
        # https://codeberg.org/OpenRGB/OpenRGB/releases
        deb: "https://codeberg.org/OpenRGB/OpenRGB/releases/download/\
          release_candidate_1.0rc2/openrgb_1.0rc2_amd64_trixie_0fca93e.deb"
