---
- hosts: localhost
  vars:
    bfg_repo_cleaner_version: 1.13.0
    shfmt_version: 3.2.0
    terraform_version: 0.13.5

  tasks:
    - name: ensure manually installed dependencies
      apt:
        name:
          - ansible
          - git
          - sudo
        update_cache: yes

    - name: install other packages
      apt:
        name:
          - ansible-lint
          - default-jre-headless
          - dnsutils
          - docker-compose
          - docker.io
          - font-manager
          - jq
          - pcscd
          - postgresql-client
          - pwgen
          - python3
          - python3-pip
          - python3-setuptools
          - python3-virtualenv
          - ripgrep
          - scdaemon
          - shellcheck
          - tmux
          - urlwatch
          - vim
          - zsh

    - name: install python dependencies
      pip:
        name:
          - azure-identity
          - azure-mgmt-compute
          - azure-mgmt-network
          - pipenv
          - yapf
        executable: pip3

    - name: install terraform
      unarchive:
        src: https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip
        remote_src: yes
        dest: /usr/local/bin
        mode: 0755
        owner: root
        group: root

    - name: install shfmt
      get_url:
        url: https://github.com/mvdan/sh/releases/download/v{{ shfmt_version }}/shfmt_v{{ shfmt_version }}_linux_amd64
        remote_src: yes
        dest: /usr/local/bin/shfmt
        mode: 0755
        owner: root
        group: root

    - name: ensure extra directories
      file: path={{ item }} state=directory mode=0755 owner=root group=root
      loop:
        - /usr/local/share/java

    - name: install repo cleaner (https://rtyley.github.io/bfg-repo-cleaner/)
      get_url:
        url: https://repo1.maven.org/maven2/com/madgag/bfg/{{ bfg_repo_cleaner_version }}/bfg-{{ bfg_repo_cleaner_version  }}.jar
        dest: /usr/local/share/java/bfg.jar
        mode: 0644
        owner: root
        group: root

    - name: ensure /etc/hosts entries
      lineinfile: path=/etc/hosts line={{ item }}
      loop:
        - 10.247.40.10 gdx-ds-app1
        - 10.247.40.11 gdx-ds-hpc1
        - 10.247.40.13 gdx-ds-node1
        - 10.247.40.14 gdx-ds-node2

  roles:
    - azure-cli
    - github-cli
    - resolved
    - sudo
