---
- name: Configuring Debian system
  hosts: localhost
  connection: local
  become: true

  roles:
    - role: base
    - role: chrome
    # - role: cloudflarewarp
    - role: desktop
    - role: firefox
    - role: gaming
    - role: media
    - role: mega
    - role: mullvadvpn
    - role: onepassword
    - role: tailscale
    - role: waydroid

  tasks:
    - name: Installing Discord
      ansible.builtin.apt:
        # curl -sI \
        #   'https://discord.com/api/download?platform=linux&format=deb' | \
        # grep -i location
        deb: https://dl.discordapp.net/apps/linux/0.0.111/discord-0.0.111.deb

    # TODO: this will be in forky
    - name: Installing OpenRGB
      ansible.builtin.apt:
        # https://gitlab.com/CalcProgrammer1/OpenRGB/-/releases
        deb: "https://openrgb.org/releases/\
          release_0.9/openrgb_0.9_amd64_bookworm_b5f46e3.deb"
