---
- hosts: localhost
  vars:
    bfg_repo_cleaner_version: 1.13.0
    terraform_version: 0.13.4

  tasks:
    - name: ensure manually installed dependencies
      apt:
        name:
          - ansible
          - git
          - sudo
        update_cache: yes

    - name: install other packages
      apt:
        name:
          - default-jre-headless
          - font-manager
          - jq
          - pcscd
          - postgresql-client
          - pwgen
          - python3
          - python3-pip
          - python3-setuptools
          - python3-virtualenv
          - scdaemon
          - tmux
          - urlwatch
          - vim
          - zsh

    - name: install python dependencies
      pip:
        name:
          - pipenv
        executable: pip3

    - name: install terraform
      unarchive:
        src: https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip
        remote_src: yes
        dest: /usr/local/bin
        mode: 0755
        owner: root
        group: root

    - name: ensure extra directories
      file: path={{ item}} state=directory mode=0755 owner=root group=root
      loop:
        - /usr/local/share/java

    - name: install repo cleaner (https://rtyley.github.io/bfg-repo-cleaner/)
      get_url:
        url: https://repo1.maven.org/maven2/com/madgag/bfg/{{ bfg_repo_cleaner_version }}/bfg-{{ bfg_repo_cleaner_version  }}.jar
        dest: /usr/local/share/java/bfg.jar
        mode: 0644
        owner: root
        group: root

  roles:
    - azure-cli
    - github-cli
