---
- name: Configuring Debian system
  hosts: localhost
  connection: local
  become: true

  roles:
    - role: base
    - role: chrome
      when: mtype != 'server'
    # - role: cloudflarewarp
    #   when: mtype != 'server'
    - role: desktop
      when: mtype != 'server'
    # - role: dropbox
    #   when: mtype != 'server'
    - role: firefox
      when: mtype != 'server'
    - role: gaming
      when: mtype != 'server'
    - role: media
      when: mtype != 'server'
    - role: mega
      when: mtype != 'server'
    - role: mullvadvpn
      when: mtype != 'server'
    - role: onepassword
      when: mtype != 'server'
    - role: server
      when: mtype == 'server'
    - role: tailscale
    - role: waydroid
      when: mtype != 'server'

  tasks:
    - name: Installing Discord
      when: mtype != 'server'
      ansible.builtin.apt:
        # curl -sI \
        #   'https://discord.com/api/download?platform=linux&format=deb' | \
        # grep -i location
        deb: https://dl.discordapp.net/apps/linux/0.0.111/discord-0.0.111.deb

    # TODO: this will be in forky
    - name: Installing OpenRGB
      when: mtype != 'server'
      ansible.builtin.apt:
        # https://codeberg.org/OpenRGB/OpenRGB/releases
        deb: "https://codeberg.org/OpenRGB/OpenRGB/releases/download/\
          release_candidate_1.0rc2/openrgb_1.0rc2_amd64_trixie_0fca93e.deb"
