---
- hosts: localhost
  vars:
    bfg_repo_cleaner_version: 1.14.0
    helm_version: 3.6.3
    helmfile_version: 0.140.0
    kubectl_version: 1.22.1
    kubectx_version: 0.9.4
    shfmt_version: 3.3.1
    sops_version: 3.7.1
    terraform_version: 1.0.6

  tasks:
    - name: ensure manually installed dependencies
      ansible.builtin.apt:
        name:
          - ansible
          - curl
          - git
          - sudo
        update_cache: true

    - name: install other packages
      ansible.builtin.apt:
        name:
          - ansible-lint
          - default-jre-headless
          - bat
          - bind9-dnsutils
          - docker-compose
          - docker.io
          - fd-find
          - font-manager
          - fzf
          - golang
          - htop
          - jq
          - libarchive-tools
          - neofetch
          - nodejs
          - npm
          - pcscd
          - postgresql-client
          - pwgen
          - python3
          - python3-pip
          - python3-setuptools
          - ripgrep
          - rustc
          - rsync
          - scdaemon
          - shellcheck
          - silversearcher-ag
          - tabix
          - tmux
          - universal-ctags
          - urlwatch
          - vim
          - virtualenv
          - whois
          - zoxide
          - xz-utils
          - zsh
          - zsh-autosuggestions
          - zsh-syntax-highlighting

    - name: install python dependencies
      ansible.builtin.pip:
        name:
          - azure-identity
          - azure-mgmt-compute
          - azure-mgmt-network
          - pipenv
          - yapf
        executable: pip3

    - name: install terraform
      ansible.builtin.unarchive:
        src: https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip
        remote_src: true
        dest: /usr/local/bin
        mode: 0755
        owner: root
        group: root

    - name: install shfmt
      ansible.builtin.get_url:
        url: https://github.com/mvdan/sh/releases/download/v{{ shfmt_version }}/shfmt_v{{ shfmt_version }}_linux_amd64
        dest: /usr/local/bin/shfmt
        mode: 0755
        owner: root
        group: root

    - name: install sops
      ansible.builtin.get_url:
        url: https://github.com/mozilla/sops/releases/download/v{{ sops_version }}/sops-v{{ sops_version }}.linux
        dest: /usr/local/bin/sops
        mode: 0755
        owner: root
        group: root

    - name: ensure extra directories
      ansible.builtin.file: path={{ item }} state=directory mode=0755 owner=root group=root
      loop:
        - /usr/local/share/java

    - name: install repo cleaner (https://rtyley.github.io/bfg-repo-cleaner/)
      ansible.builtin.get_url:
        url: https://repo1.maven.org/maven2/com/madgag/bfg/{{ bfg_repo_cleaner_version }}/bfg-{{ bfg_repo_cleaner_version  }}.jar
        dest: /usr/local/share/java/bfg.jar
        mode: 0644
        owner: root
        group: root

    - name: ensure /etc/hosts entries
      ansible.builtin.lineinfile: path=/etc/hosts line={{ item }}
      loop:
        - 10.247.40.10 gdx-ds-app1
        - 10.247.40.11 gdx-ds-hpc1
        - 10.247.40.13 gdx-ds-node1
        - 10.247.40.14 gdx-ds-node2
        - 10.247.40.12 gdx-ds-db1
        - 192.168.9.159 gdx-ds-vm01

  roles:
    - azure-cli
    - github-cli
    - k8s
    - resolved
    - sudo

# vim: ft=yaml.ansible
