---
- name: Configure debian system
  hosts: localhost
  connection: local
  vars:
    bfg_repo_cleaner_version: 1.14.0
    helm_version: 3.11.1
    helmfile_version: 0.151.0
    kubectl_version: 1.26.2
    kubectx_version: 0.9.4
    shfmt_version: 3.6.0
    sops_version: 3.7.3
    terraform_version: 1.3.9

  tasks:
    - name: Ensure manually installed dependencies
      ansible.builtin.apt:
        name:
          - ansible
          - curl
          - git
          - sudo
        update_cache: true

    - name: Install other packages
      ansible.builtin.apt:
        name:
          - ansible-lint
          - bat
          - bind9-dnsutils
          - default-jre-headless
          - docker-compose
          - docker.io
          - fd-find
          - font-manager
          - fzf
          - golang
          - htop
          - jq
          - libarchive-tools
          - neofetch
          - nodejs
          - npm
          - pcscd
          - postgresql-client
          - pwgen
          - python3
          - python3-pip
          - python3-setuptools
          - ripgrep
          - rsync
          - rustc
          - scdaemon
          - shellcheck
          - silversearcher-ag
          - tabix
          - tmux
          - universal-ctags
          - urlwatch
          - vim
          - virtualenv
          - whois
          - xz-utils
          - zoxide
          - zsh
          - zsh-autosuggestions
          - zsh-syntax-highlighting

    - name: Install python dependencies
      ansible.builtin.pip:
        executable: pip3
        name:
          - azure-identity
          - azure-mgmt-compute
          - azure-mgmt-network
          - pipenv
          - yapf

    - name: Install terraform
      ansible.builtin.unarchive:
        dest: /usr/local/bin
        group: root
        mode: "0755"
        owner: root
        remote_src: true
        src: https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip

    - name: Install shfmt
      ansible.builtin.get_url:
        dest: /usr/local/bin/shfmt
        group: root
        mode: "0755"
        owner: root
        url: https://github.com/mvdan/sh/releases/download/v{{ shfmt_version }}/shfmt_v{{ shfmt_version }}_linux_amd64

    - name: Install sops
      ansible.builtin.get_url:
        dest: /usr/local/bin/sops
        group: root
        mode: "0755"
        owner: root
        url: https://github.com/mozilla/sops/releases/download/v{{ sops_version }}/sops-v{{ sops_version }}.linux

    - name: Ensure extra directories
      ansible.builtin.file:
        group: root
        mode: "0755"
        owner: root
        path: "{{ item }}"
        state: directory
      loop:
        - /usr/local/share/java

    - name: Install repo cleaner (https://rtyley.github.io/bfg-repo-cleaner/)
      ansible.builtin.get_url:
        dest: /usr/local/share/java/bfg.jar
        group: root
        mode: "0644"
        owner: root
        url: https://repo1.maven.org/maven2/com/madgag/bfg/{{ bfg_repo_cleaner_version }}/bfg-{{ bfg_repo_cleaner_version }}.jar

    - name: Ensure /etc/hosts entries
      ansible.builtin.lineinfile:
        line: "{{ item }}"
        path: /etc/hosts
      loop:
        - 10.247.40.10 gdx-ds-app1
        - 10.247.40.11 gdx-ds-hpc1
        - 10.247.40.12 gdx-ds-db1
        - 10.247.40.13 gdx-ds-node1
        - 10.247.40.14 gdx-ds-node2
        - 192.168.9.159 gdx-ds-vm01

  roles:
    - azure-cli
    - github-cli
    - k8s
    - resolved
    - sudo

# vim: ft=yaml.ansible
