---
- name: Configuring Debian system
  hosts: localhost
  connection: local
  become: true

  roles:
    - role: base
    - role: chrome
    - role: desktop
    - role: gaming
    - role: media
    - role: mega
    - role: mullvadvpn
    - role: onepassword
    - role: tailscale

  tasks:
    - name: Installing Discord
      ansible.builtin.apt:
        # curl -sI \
        #   'https://discord.com/api/download?platform=linux&format=deb' | \
        # grep -i location
        deb: https://dl.discordapp.net/apps/linux/0.0.38/discord-0.0.38.deb
