#!/bin/bash -e

sudo apt update
sudo apt upgrade -y
sudo apt install -y ansible git

wdir="$(mktemp -d)"
sdir="$(pwd)"
cd "$wdir"

echo "%sudo ALL=(ALL:ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/gsudo
sudo chmod 0440 /etc/sudoers.d/gsudo

git clone https://github.com/mfinelli/arch-install.git
cd arch-install/debian

./run.bash

cd "$sdir"
rm -rf "$wdir"

exit 0
