#!/bin/bash -e

# base install doesn't come with sudo :(
su -c 'apt-get update && apt-get upgrade -y && apt-get install -y sudo'
su -c 'echo "mario ALL=(ALL:ALL) NOPASSWD:ALL" | tee /etc/sudoers.d/mario'
su -c 'chmod 0400 /etc/sudoers.d/mario'

sudo apt-get install -y ansible git

wdir="$(mktemp -d)"
sdir="$(pwd)"
cd "$wdir"

git clone https://github.com/mfinelli/arch-install.git
cd arch-install/debian

sudo ansible-playbook debian.yml

cd "$sdir"
rm -rf "$wdir"

exit 0
