---
- hosts: localhost
  roles:
    - role: ansible
      tags: [all, init, setup]
    - role: base
      tags: [all, setup]
    - role: unbound
      tags: [all, setup]
    - role: main
      tags: [all]
    - role: dev
      tags: [all]
    - role: media
      tags: [all]
    - role: databases
      tags: [all]
    - role: work
      tags: [all]
      when: mtype == 'work'
