---
- name: Configuring Archlinux system
  hosts: localhost
  connection: local

  roles:
    - role: base
      tags: [all, setup]
    - role: desktop
      tags: [all]
      when: mtype != 'server'
    - role: main
      tags: [all]
    - role: dev
      tags: [all]
    - role: media
      tags: [all]
    - role: work
      tags: [all]
      when: mtype == 'work'
    - role: server
      tags: [all]
      when: mtype == 'server'
