#!/bin/bash -e

wdir="$(mktemp -d)"
sdir="$(pwd)"
cd "$wdir"

git clone https://github.com/mfinelli/arch-install.git
cd arch-install/arch

if lspci | grep VGA | grep -qi amd; then
  gcard=amd
elif lspci | grep VGA | grep -qi intel; then
  gcard=intel
else
  gcard=none
fi

ansible-playbook \
  --extra-vars gcard=$gcard \
  --extra-vars multilib=true \
  arch.yml

cd "$sdir"
rm -rf "$wdir"

exit 0
