#!/bin/bash

set -e

wdir="$(mktemp -d)"
sdir="$(pwd)"
cd "$wdir"

git clone https://github.com/mfinelli/arch-install.git
cd arch-install/arch

# clear out old initramfs images -- we'll be creating a UKI
sudo rm -rf /boot/initramfs-linux*

./run.bash setup

cd "$sdir"
rm -rf "$wdir"

exit 0
