#!/bin/bash -ex

if [[ $# -ne 0 ]]; then
  echo >&2 "usage: $(basename "$0")"
  exit 1
fi

# use a known good mirror for initial package installation - we'll generate a
# new mirrorlist shortly
# shellcheck disable=SC2016
MIRROR='Server = https://mirrors.kernel.org/archlinux/$repo/os/$arch'
echo "$MIRROR" | sudo tee /etc/pacman.d/mirrorlist

# add the supermario repo and then refresh - we'll set it "correctly" once
# ansible runs
curl -s https://finelli.pub/36FDA306.asc | sudo pacman-key -a -
sudo pacman-key --lsign-key C3CD75B002978A8468CA7B1F6C3ADDDE36FDA306
echo '[supermario]' | sudo tee -a /etc/pacman.conf
# shellcheck disable=SC2016
echo 'Server = https://pkgs.finelli.dev/arch/$arch' |
  sudo tee -a /etc/pacman.conf
pacman -Syyu

# the rest of the system gets installed/configured using ansible
pacman -S ansible git pyalpm python-py-cpuinfo \
  ansible-{aur,gpg-key-git,gsetting-git}

exit 0
