---
- name: Adding the MEGA repository signing key
  ansible.builtin.apt_key:
    keyring: /usr/share/keyrings/meganz-archive-keyring.gpg
    state: present
    # url: https://mega.nz/keys/MEGA_signing.key
    url: "{{ mega_repo_host }}\
      Debian_{{ ansible_distribution_major_version }}/Release.key"

- name: Adding the MEGA repository
  ansible.builtin.apt_repository:
    filename: megasync
    repo: >
      deb [signed-by=/usr/share/keyrings/meganz-archive-keyring.gpg]
      {{ mega_repo_host }}Debian_{{ ansible_distribution_major_version }}/ ./
    update_cache: true

- name: Installing MEGASync
  ansible.builtin.apt:
    name: megasync
    state: present
