---
- name: Install NetworkManager configuration
  ansible.builtin.copy:
    dest: /etc/NetworkManager/NetworkManager.conf
    group: root
    mode: "0644"
    owner: root
    src: NetworkManager.conf
  notify:
    - Restart NetworkManager

- name: Ensure systemd-resolved is running and enabled
  ansible.builtin.systemd:
    enabled: true
    name: systemd-resolved
    state: started

- name: Symlink the systemd resolv.conf stub
  ansible.builtin.file:
    dest: /etc/resolv.conf
    force: true # overwrite existing non-symlink file
    src: /run/systemd/resolve/stub-resolv.conf
    state: link

- name: Ensure resolved.conf.d directory
  ansible.builtin.file:
    group: root
    mode: "0755"
    owner: root
    path: /etc/systemd/resolved.conf.d
    state: directory

- name: Copy custom systemd-resolved configuration
  ansible.builtin.copy:
    dest: /etc/systemd/resolved.conf.d/dns.conf
    group: root
    mode: "0644"
    owner: root
    src: resolved.conf
  notify:
    - Restart systemd-resolved
