---
tailscale_ssh:
  - homepi
  - parkpi
  - raipi
  - tvpi
  - workpi

tailscale_tags:
  homepi:
    - tag:homeassistant
  parkpi:
    - tag:vpn
  raipi:
    - tag:vpn
  tvpi:
    - tag:service
  workpi:
    - tag:service
