---
# there might be a better way but this works pretty well
# https://serverfault.com/q/881908
- name: Check if this host uses a keyfile
  when: fde == 'true'
  tags: fde
  block:
    - name: Default keyfile to false
      ansible.builtin.set_fact:
        crypttab_keyfile: false

    - name: Check if a keyfile exists in the root
      ansible.builtin.stat:
        path: /root/cryptkey
      register: crypttab_cryptkey

    - name: Update keyfile setting
      ansible.builtin.set_fact:
        crypttab_keyfile: true
      when: crypttab_cryptkey.stat.exists

- name: Install kernel boot config
  ansible.builtin.template:
    dest: /boot/config.txt
    owner: root
    group: root
    mode: "0755" # all rpi files in /boot are +x
    src: config.txt.j2
  tags: fde

- name: Install kernel command line config
  ansible.builtin.template:
    dest: /boot/cmdline.txt
    owner: root
    group: root
    mode: "0755" # all rpi files in /boot are +x
    src: cmdline.txt.j2
  tags: fde

- name: Install updated fstab
  ansible.builtin.template:
    dest: /etc/fstab
    owner: root
    group: root
    mode: "0644"
    src: fstab.j2
  tags: fde

- name: Install updated crypttab
  when: fde == 'true'
  ansible.builtin.template:
    dest: /etc/crypttab
    owner: root
    group: root
    mode: "0644"
    src: crypttab.j2
  tags: fde
