---
# there might be a better way but this works pretty well
# https://serverfault.com/q/881908
- name: Checking if this host uses a keyfile
  when: fde == 'true'
  tags: fde
  block:
    - name: Setting keyfile default to false
      ansible.builtin.set_fact:
        main_crypttab_keyfile: false

    - name: Checking if a keyfile exists under root
      ansible.builtin.stat:
        path: /root/cryptkey
      register: main_crypttab_cryptkey

    - name: Updating keyfile setting
      ansible.builtin.set_fact:
        main_crypttab_keyfile: true
      when: main_crypttab_cryptkey.stat.exists

- name: Copying kernel boot configuration
  ansible.builtin.template:
    dest: /boot/config.txt
    group: root
    mode: "0755" # all rpi files in /boot are +x
    owner: root
    src: config.txt.j2
  tags: fde

- name: Copying kernel command line configuration
  ansible.builtin.template:
    dest: /boot/cmdline.txt
    group: root
    mode: "0755" # all rpi files in /boot are +x
    owner: root
    src: cmdline.txt.j2
  tags: fde

- name: Copying updated fstab
  ansible.builtin.template:
    dest: /etc/fstab
    group: root
    mode: "0644"
    owner: root
    src: fstab.j2
  tags: fde

- name: Copying updated crypttab
  when: fde == 'true'
  ansible.builtin.template:
    dest: /etc/crypttab
    group: root
    mode: "0644"
    owner: root
    src: crypttab.j2
  tags: fde
