---
- name: Checking if devices exist
  when: ansible_hostname in main_attached_storage
  ansible.builtin.stat:
    path: /dev/disk/by-partlabel/{{ item.label }}
    get_mime: false
    get_attributes: false
    get_checksum: false
  loop: "{{ main_attached_storage[ansible_hostname] }}"
  register: main_attached_storage_device_lookup

- name: Checking if keyfiles exist
  when: ansible_hostname in main_attached_storage
  ansible.builtin.stat:
    path: "{{ item.keyfile }}"
    get_mime: false
    get_attributes: false
    get_checksum: false
  loop: "{{ main_attached_storage[ansible_hostname] }}"
  register: main_attached_storage_keyfile_lookup

- name: Setting fact for easier lookup
  ansible.builtin.set_fact:
    main_attached_storage_lookups: {}

- name: Building lookups variable
  when: ansible_hostname in main_attached_storage
  ansible.builtin.set_fact:
    main_attached_storage_lookups: '{{ main_attached_storage_lookups |
      combine({item.name: {"device":
      (main_attached_storage_device_lookup.results |
      selectattr(''item.name'', ''=='', item.name) | map(attribute=''stat'') |
      first).exists, "keyfile":
      (main_attached_storage_keyfile_lookup.results |
      selectattr(''item.name'', ''=='', item.name) | map(attribute=''stat'') |
      first).exists}}, recursive=True) }}'
  loop: "{{ main_attached_storage[ansible_hostname] }}"
