---
- name: Install firewall software
  become: true
  community.general.pacman:
    name:
      - ufw
      - sshguard

- name: Start and enable ufw
  become: true
  ansible.builtin.systemd:
    name: ufw.service
    state: started
    enabled: true

- name: Start and enable sshguard
  become: true
  ansible.builtin.systemd:
    name: sshguard.service
    state: started
    enabled: true

- name: Set default ufw policy to deny
  become: true
  community.general.ufw:
    state: enabled
    policy: deny

- name: Allow ssh traffic
  become: true
  community.general.ufw:
    rule: allow
    port: 22
    proto: tcp

- name: Install ufw before rules
  become: true
  ansible.builtin.copy:
    dest: /etc/ufw/{{ item }}.rules
    owner: root
    group: root
    mode: "0640"
    src: "{{ item }}.rules"
  loop:
    - before
    - before6
  notify:
    - Restart ufw

- name: Install sshd_config
  become: true
  ansible.builtin.copy:
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: "0644"
    src: sshd_config
  notify:
    - Restart sshd

- name: Install server software
  become: true
  community.general.pacman:
    name:
      - screen
