---
- name: Installing firewall packages
  become: true
  community.general.pacman:
    name:
      - sshguard
      - ufw
    state: present

- name: Enabling "ufw" service
  become: true
  ansible.builtin.systemd:
    enabled: true
    name: ufw.service
    state: started

- name: Enabling sshguard service
  become: true
  ansible.builtin.systemd:
    enabled: true
    name: sshguard.service
    state: started

- name: Setting the default ufw policy to deny
  become: true
  community.general.ufw:
    policy: deny
    state: enabled

- name: Adding ufw rule to allow SSH traffic
  become: true
  community.general.ufw:
    port: 22
    proto: tcp
    rule: allow

- name: Copying ufw "before" rules # enables sshguard
  become: true
  ansible.builtin.copy:
    dest: /etc/ufw/{{ item }}.rules
    group: root
    mode: "0640"
    owner: root
    src: "{{ item }}.rules"
  loop:
    - before
    - before6
  notify:
    - Restart ufw

- name: Copying sshd configuration
  become: true
  ansible.builtin.copy:
    dest: /etc/ssh/sshd_config
    group: root
    mode: "0644"
    owner: root
    src: sshd_config
    validate: sshd -tf %s
  notify:
    - Restart sshd

- name: Installing screen
  become: true
  community.general.pacman:
    name: screen
    state: present
