---
- name: Install kubectl
  ansible.builtin.get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/v{{ kubectl_version }}/bin/linux/amd64/kubectl
    dest: /usr/local/bin/kubectl
    mode: "0755"
    owner: root
    group: root
  notify:
    - Install kubectl bash completion
    - Install kubectl zsh completion

- name: Install helm
  ansible.builtin.unarchive:
    src: https://get.helm.sh/helm-v{{ helm_version }}-linux-amd64.tar.gz
    remote_src: true
    dest: /usr/local/bin
    mode: "0755"
    owner: root
    group: root
    extra_opts:
      - --strip-components=1
  notify:
    - Install helm bash completion
    - Install helm zsh completion

- name: Remove extra helm files
  ansible.builtin.file:
    path: /usr/local/bin/{{ item }}
    state: absent
  loop:
    - LICENSE
    - README.md

- name: Install helmfile
  ansible.builtin.get_url:
    url: https://github.com/roboll/helmfile/releases/download/v{{ helmfile_version }}/helmfile_linux_amd64
    dest: /usr/local/bin/helmfile
    mode: "0755"
    owner: root
    group: root

- name: Install kubectx
  ansible.builtin.include_tasks: kubectx.yml
