---
- name: install azure-cli dependencies
  apt:
    name:
      - ca-certificates
      - curl
      - apt-transport-https
      - lsb-release
      - gnupg
    update_cache: yes

- name: download and install the microsoft signing key
  shell: |
    curl -sL https://packages.microsoft.com/keys/microsoft.asc | \
    gpg --dearmor | \
    tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null
  args:
    creates: /etc/apt/trusted.gpg.d/microsoft.gpg
    warn: false

- name: add the azure cli repository
  template:
    dest: /etc/apt/sources.list.d/azure-cli.list
    owner: root
    group: root
    mode: 0644
    src: azure-cli.list.j2

- name: install the azure-cli
  apt:
    name:
      - azure-cli
    update_cache: yes
