---
- name: install azure-cli dependencies
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - apt-transport-https
      - lsb-release
      - gnupg
    update_cache: yes

- name: download and install the microsoft signing key
  ansible.builtin.shell
    set -o pipefail
    curl -sL https://packages.microsoft.com/keys/microsoft.asc | \
    gpg --dearmor | \
    tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null
  args:
    creates: /etc/apt/trusted.gpg.d/microsoft.gpg
    executable: /bin/bash
    warn: false

- name: add the azure cli repository
  ansible.builtin.template:
    dest: /etc/apt/sources.list.d/azure-cli.list
    owner: root
    group: root
    mode: 0644
    src: azure-cli.list.j2

- name: install the azure-cli
  ansible.builtin.apt:
    name:
      - azure-cli
    update_cache: yes

- name: download azcopy
  ansible.builtin.unarchive:
    # curl -sI https://aka.ms/downloadazcopy-v10-linux | grep -i location
    src: https://azcopyvnext.azureedge.net/release20210616/azcopy_linux_amd64_10.11.0.tar.gz
    remote_src: yes
    dest: /usr/local/bin
    mode: 0755
    owner: root
    group: root
    extra_opts:
      - --strip-components=1

- name: remove extra azcopy files
  ansible.builtin.file:
    path: /usr/local/bin/{{ item }}
    state: absent
  loop:
    - NOTICE.txt
