---
- name: Install azure-cli dependencies
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    update_cache: true

- name: Add the microsoft signing key
  ansible.builtin.apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc

- name: Add the azure cli repository
  ansible.builtin.apt_repository:
    filename: azure-cli
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ {{ ansible_distribution_release }} main

- name: Install the azure-cli
  ansible.builtin.apt:
    name:
      - azure-cli
    update_cache: true

- name: Download azcopy
  ansible.builtin.unarchive:
    dest: /usr/local/bin
    extra_opts:
      - --strip-components=1
    group: root
    mode: "0755"
    owner: root
    remote_src: true

    # curl -sI https://aka.ms/downloadazcopy-v10-linux | grep -i location
    src: https://azcopyvnext.azureedge.net/release20230123/azcopy_linux_amd64_10.17.0.tar.gz

- name: Remove extra azcopy files
  ansible.builtin.file:
    path: /usr/local/bin/{{ item }}
    state: absent
  loop:
    - NOTICE.txt
