---
- name: Adding Google Chrome signing key
  ansible.builtin.apt_key:
    keyring: /usr/share/keyrings/google-chrome-archive-keyring.gpg
    state: present
    url: https://dl.google.com/linux/linux_signing_key.pub

- name: Adding Google Chrome repository
  ansible.builtin.apt_repository:
    filename: google-chrome
    repo: >
      deb [arch=amd64
      signed-by=/usr/share/keyrings/google-chrome-archive-keyring.gpg]
      https://dl.google.com/linux/chrome/deb/ stable main
    state: present
    update_cache: true

- name: Installing Google Chrome
  ansible.builtin.apt:
    name: google-chrome-stable
    state: present
