---
# The chrome download page says you can disable the chrome repo if this file
# exists, but reading through the `postinst` script I'm not convinced... but
# we'll try it anyway
- name: Adding Google Chrome defaults file
  ansible.builtin.file:
    group: root
    mode: "0644"
    owner: root
    path: /etc/default/google-chrome
    state: touch

- name: Downloading Google Chrome signing key
  ansible.builtin.get_url:
    dest: /etc/apt/keyrings/google-archive-keyring.asc
    group: root
    mode: "0644"
    owner: root
    url: https://dl.google.com/linux/linux_signing_key.pub
  register: chrome_repository_key

- name: Adding Google Chrome signing key
  ansible.builtin.command:
    cmd: >-
      gpg --dearmor -o /usr/share/keyrings/google-archive-keyring.gpg
      /etc/apt/keyrings/google-archive-keyring.asc
    creates: "{{ chrome_repository_key.changed | ternary('',
      '/usr/share/keyrings/google-archive-keyring.gpg') | default(omit,
      true) }}"

- name: Adding Google Chrome repository
  ansible.builtin.template:
    dest: /etc/apt/sources.list.d/google-chrome.sources
    group: root
    mode: "0644"
    owner: root
    src: google-chrome.sources.j2
  register: chrome_repository

- name: Installing Google Chrome
  ansible.builtin.apt:
    name: google-chrome-stable
    state: present
    update_cache: "{{ chrome_repository.changed }}"

- name: Removing automatic Google Chrome sources list
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/google-chrome.list
    state: absent
