---
- name: Add github signing key
  ansible.builtin.apt_key:
    id: C99B11DEB97541F0
    keyserver: keyserver.ubuntu.com

- name: Add the github cli repo
  ansible.builtin.apt_repository:
    filename: github-cli
    repo: deb https://cli.github.com/packages {{ ansible_distribution_release }} main

- name: Install github-cli
  ansible.builtin.apt:
    name: gh
    update_cache: true
