---
- name: Adding the Tailscale signing key
  ansible.builtin.apt_key:
    keyring: /usr/share/keyrings/tailscale-archive-keyring.gpg
    state: present
    url: "https://pkgs.tailscale.com/stable/debian/\
      {{ ansible_distribution_release }}.gpg"

- name: Adding the Tailscale repository
  ansible.builtin.apt_repository:
    filename: tailscale
    repo: >
      deb [signed-by=/usr/share/keyrings/tailscale-archive-keyring.gpg]
      https://pkgs.tailscale.com/stable/debian
      {{ ansible_distribution_release }} main
    update_cache: true

- name: Installing Tailscale
  ansible.builtin.apt:
    name: tailscale
    state: present

- name: Adding firewall rule to allow incoming traffic to Tailscale interface
  community.general.ufw:
    direction: in
    interface: tailscale0
    rule: allow

- name: Adding firewall rule to allow UDP traffic on port 41641
  community.general.ufw:
    port: "41641"
    proto: udp
    rule: allow

- name: Adding firewall rule to allow UDP traffic on port 3478
  community.general.ufw:
    port: "3478"
    proto: udp
    rule: allow
