---
- name: Adding the Tailscale signing key
  ansible.builtin.get_url:
    dest: /usr/share/keyrings/tailscale-archive-keyring.gpg
    group: root
    mode: "0644"
    owner: root
    url: "https://pkgs.tailscale.com/stable/debian/\
      {{ ansible_distribution_release }}.noarmor.gpg"

- name: Adding the Tailscale repository
  ansible.builtin.template:
    dest: /etc/apt/sources.list.d/tailscale.sources
    group: root
    mode: "0644"
    owner: root
    src: tailscale.sources.j2
  register: tailscale_repository

- name: Installing Tailscale
  ansible.builtin.apt:
    name: tailscale
    state: present
    update_cache: "{{ tailscale_repository.changed }}"

- name: Adding firewall rule to allow incoming traffic to Tailscale interface
  community.general.ufw:
    direction: in
    interface: tailscale0
    rule: allow

- name: Adding firewall rule to allow UDP traffic on port 41641
  community.general.ufw:
    port: "41641"
    proto: udp
    rule: allow

- name: Adding firewall rule to allow UDP traffic on port 3478
  community.general.ufw:
    port: "3478"
    proto: udp
    rule: allow
