---
- name: Checking if the i386 architecture is enabled
  ansible.builtin.shell: >
    set -e -o pipefail;
    dpkg --print-foreign-architectures | grep i386
  args:
    executable: /bin/bash
  register: gaming_i386_enabled
  changed_when: gaming_i386_enabled.rc == 1
  failed_when: gaming_i386_enabled.rc > 1

- name: Enabling the i386 architecture
  ansible.builtin.command: dpkg --add-architecture i386
  when: gaming_i386_enabled.rc == 1
  register: gaming_i386_was_enabled
  changed_when: gaming_i386_was_enabled.rc == 0
  failed_when: gaming_i386_was_enabled.rc != 0

- name: Installing Wine
  ansible.builtin.include_tasks: wine.yml

- name: Installing Steam
  ansible.builtin.include_tasks: steam.yml

- name: Installing Lutris
  ansible.builtin.include_tasks: lutris.yml

- name: Installing ludusavi
  ansible.builtin.include_tasks: ludusavi.yml

- name: Installing Virtualbox
  ansible.builtin.apt:
    name:
      - virtualbox
      - virtualbox-guest-additions-iso
    state: present

- name: Installing Dolphin
  ansible.builtin.apt:
    name: dolphin-emu
    state: present

- name: Installing other gaming stuff
  ansible.builtin.apt:
    name:
      - gamemode
      - gamescope
      - mangohud
      - vkbasalt
    state: present

- name: Installing OBS Studio
  ansible.builtin.apt:
    name:
      - obs-studio
      - obs-cli
      - obs-3d-effect
      - obs-advanced-scene-switcher
      - obs-ashmanix-blur-filter
      - obs-ashmanix-countdown
      - obs-color-monitor
      - obs-command-source
      - obs-gradient-source
      - obs-move-transition
      - obs-pipewire-audio-capture
      - obs-plugin-looking-glass
      - obs-plugins
      - obs-scene-as-transition
      - obs-scene-collection-manager
      - obs-scene-notes-dock
      - obs-scene-tree-view
      - obs-source-clone
      - obs-source-copy
      - obs-time-source
      - obs-transition-table
      - obs-vintage-filter
    state: present
