---
- name: Downloading the WineHQ signing key
  ansible.builtin.get_url:
    dest: /etc/apt/keyrings/winehq-archive-keyring.asc
    group: root
    mode: "0644"
    owner: root
    url: https://dl.winehq.org/wine-builds/winehq.key
  register: gaming_winehq_repository_key

- name: Adding the WineHQ signing key
  ansible.builtin.command:
    cmd: >-
      gpg --dearmor -o /usr/share/keyrings/winehq-archive-keyring.gpg
      /etc/apt/keyrings/winehq-archive-keyring.asc
    creates: "{{ gaming_winehq_repository_key.changed | ternary('',
      '/usr/share/keyrings/winehq-archive-keyring.gpg') | default(omit,
      true) }}"

- name: Adding the WineHQ repository
  ansible.builtin.template:
    dest: /etc/apt/sources.list.d/winehq.sources
    group: root
    mode: "0644"
    owner: root
    src: wine.sources.j2
  register: gaming_winehq_repository

- name: Installing wine
  ansible.builtin.apt:
    install_recommends: true
    name:
      - fonts-wine
      # - winehq-stable
      - winehq-staging
    state: present
    update_cache: "{{ gaming_winehq_repository.changed }}"
