---
- name: Installing fonts
  become: true
  community.general.pacman:
    name:
      - gnu-free-fonts
      - libertinus-font
      - noto-fonts
      - noto-fonts-emoji
      - noto-fonts-extra
      - otf-fira-mono
      - otf-fira-sans
      - ttf-bitstream-vera
      - ttf-caladea
      - ttf-carlito
      - ttf-dejavu
      - ttf-liberation
      - ttf-ubuntu-font-family
    state: present

- name: Installing fonts from the AUR
  kewlfft.aur.aur:
    name:
      # - ttf-google-fonts-git
      - ttf-symbola
    state: present
