---
- name: Install fonts
  become: true
  community.general.pacman:
    name:
      - ttf-liberation
      - ttf-bitstream-vera
      - gnu-free-fonts
      - ttf-carlito
      # - ttf-caladea
      - ttf-dejavu
      - libertinus-font
      - otf-fira-sans
      - otf-fira-mono
      - noto-fonts
      - noto-fonts-emoji
      - noto-fonts-extra
      - ttf-ubuntu-font-family

- name: Install fonts part two
  kewlfft.aur.aur:
    name:
      - ttf-symbola
      # - ttf-google-fonts-git
