---
- name: Installing audio packages
  become: true
  community.general.pacman:
    name:
      - alsa-plugins
      - alsa-utils
      - easyeffects
      - pavucontrol
      - pipewire
      - pipewire-alsa
      - pipewire-docs
      - pipewire-pulse
      - wireplumber
    state: present

- name: Installing keymapper
  become: true
  community.general.pacman:
    name: keymapper
    state: present

- name: Enabling keymapperd service
  become: true
  ansible.builtin.systemd:
    enabled: true
    name: keymapperd.service
    state: started

- name: Installing bluetooth packages
  become: true
  community.general.pacman:
    name:
      - blueman
      - bluez
      - bluez-utils
    state: present

- name: Enabling bluetooth
  become: true
  ansible.builtin.systemd:
    enabled: true
    name: bluetooth.service

- name: Installing baseline desktop packages
  become: true
  community.general.pacman:
    name:
      - firefox
      - firefox-i18n-en-us
      - firefox-i18n-es-es
      - firefox-i18n-fr
      - firefox-i18n-it
      - openssh
    state: present

- name: Installing piper
  become: true
  community.general.pacman:
    name: piper
    state: present

- name: Installing GNOME desktop environment
  ansible.builtin.include_tasks: gnome.yml
  when: mtype != 'media'

- name: Installing XFCE desktop environment
  ansible.builtin.include_tasks: xfce.yml
  when: mtype == 'media'

- name: Installing printing packages
  ansible.builtin.include_tasks: printing.yml
  when: mtype != 'media'

- name: Installing fonts
  ansible.builtin.include_tasks: fonts.yml
