---
- name: Install audio packages
  become: true
  community.general.pacman:
    name:
      - alsa-plugins
      - alsa-utils
      - easyeffects
      - pavucontrol
      - pipewire
      - pipewire-alsa
      - pipewire-docs
      - pipewire-pulse
      - wireplumber

- name: Enable network manager
  become: true
  ansible.builtin.systemd:
    enabled: true
    name: NetworkManager.service

- name: Install keymapper
  become: true
  community.general.pacman:
    name: keymapper

- name: Enable keymapperd
  become: true
  ansible.builtin.systemd:
    enabled: true
    name: keymapperd.service
    state: started

- name: Install bluetooth packages
  become: true
  community.general.pacman:
    name:
      - blueman
      - bluez
      - bluez-utils

- name: Enable bluetooth
  become: true
  ansible.builtin.systemd:
    enabled: true
    name: bluetooth.service

- name: Install base packages
  become: true
  community.general.pacman:
    name:
      - firefox
      - firefox-i18n-en-us
      - firefox-i18n-es-es
      - firefox-i18n-fr
      - firefox-i18n-it
      - openssh

- name: Install GNOME desktop environment
  ansible.builtin.include_tasks: gnome.yml
  when: mtype != 'media'

- name: Install XFCE desktop environment
  ansible.builtin.include_tasks: xfce.yml
  when: mtype == 'media'

- name: Install printing packages
  ansible.builtin.include_tasks: printing.yml
  when: mtype != 'media'

- name: Install fonts
  ansible.builtin.include_tasks: fonts.yml

# - name: install cursors
#   when: mtype != 'server'
#   kewlfft.aur.aur: name=xcursor-openzone
