---
- name: install printing packages
  when: mtype != 'media'
  become: true
  community.general.pacman:
    name:
      - ghostscript
      - cups
      - cups-pdf
      - gutenprint
      - foomatic-db
      - foomatic-db-engine
      - foomatic-db-nonfree
      - foomatic-db-gutenprint-ppds
      - foomatic-db-nonfree-ppds
      - foomatic-db-ppds
      - hplip
      - splix

- name: install drivers from aur
  when: mtype != 'media'
  kewlfft.aur.aur:
    name:
      - epson-inkjet-printer-escpr
      - epson-inkjet-printer-escpr2

- name: install network printing packages
  when: mtype != 'media'
  become: true
  community.general.pacman:
    name:
      - avahi
      - samba

- name: enable printing services
  when: mtype != 'media'
  become: true
  ansible.builtin.systemd: name={{ item }} enabled=true
  loop:
    - cups.service
    - avahi-daemon.service

- name: enable scanning packages
  when: mtype != 'media'
  become: true
  community.general.pacman:
    name:
      - gscan2pdf
      - paperwork
      - tesseract
      - tesseract-data-eng
      - tesseract-data-ita
      - tesseract-data-spa
      - tesseract-data-fra

- name: install scanner driver
  when: mtype != 'media'
  kewlfft.aur.aur: name=brscan5
