---
- name: Installing printing packages
  when: mtype != 'media'
  become: true
  community.general.pacman:
    name:
      - cups
      - cups-pdf
      - foomatic-db
      - foomatic-db-engine
      - foomatic-db-gutenprint-ppds
      - foomatic-db-nonfree
      - foomatic-db-nonfree-ppds
      - foomatic-db-ppds
      - ghostscript
      - gutenprint
      - hplip
      - splix
    state: present

- name: Installing packages for networked printing
  when: mtype != 'media'
  become: true
  community.general.pacman:
    name:
      - avahi
      - samba
    state: present

- name: Enabling services to allow printing
  when: mtype != 'media'
  become: true
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
  loop:
    - avahi-daemon.service
    - cups.service

- name: Installing scanning packages
  when: mtype != 'media'
  become: true
  community.general.pacman:
    name:
      - gscan2pdf
      - paperwork
      - pdftk
      - tesseract
      - tesseract-data-eng
      - tesseract-data-fra
      - tesseract-data-ita
      - tesseract-data-spa
    state: present

- name: Installing scanner driver
  when: mtype != 'media'
  kewlfft.aur.aur:
    name: brscan5
    state: present
