---
- name: Install printing packages
  when: mtype != 'media'
  become: true
  community.general.pacman:
    name:
      - cups
      - cups-pdf
      - foomatic-db
      - foomatic-db-engine
      - foomatic-db-gutenprint-ppds
      - foomatic-db-nonfree
      - foomatic-db-nonfree-ppds
      - foomatic-db-ppds
      - ghostscript
      - gutenprint
      - hplip
      - splix

- name: Install drivers from aur
  when: mtype != 'media'
  kewlfft.aur.aur:
    name:
      - epson-inkjet-printer-escpr
      - epson-inkjet-printer-escpr2

- name: Install network printing packages
  when: mtype != 'media'
  become: true
  community.general.pacman:
    name:
      - avahi
      - samba

- name: Enable printing services
  when: mtype != 'media'
  become: true
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
  loop:
    - avahi-daemon.service
    - cups.service

- name: Enable scanning packages
  when: mtype != 'media'
  become: true
  community.general.pacman:
    name:
      - gscan2pdf
      - paperwork
      - tesseract
      - tesseract-data-eng
      - tesseract-data-fra
      - tesseract-data-ita
      - tesseract-data-spa

- name: Install scanner driver
  when: mtype != 'media'
  kewlfft.aur.aur:
    name: brscan5
