---
- name: Install xorg
  become: true
  community.general.pacman:
    name:
      - xorg-server
      - xorg-apps

- name: Install desktop environment (xfce)
  become: true
  community.general.pacman:
    name:
      - xfce4
      - xfce4-goodies
      - lightdm
      - lightdm-gtk-greeter
      - network-manager-applet
      - accountsservice
      - xdg-user-dirs
      - gvfs
      - gvfs-afc
      - gvfs-mtp
      - gnome-keyring
      - seahorse

- name: Install lightdm configuration
  become: true
  ansible.builtin.template:
    src: lightdm.conf.j2
    dest: /etc/lightdm/lightdm.conf
    owner: root
    group: root
    mode: "0644"

- name: Enable lightdm
  become: true
  ansible.builtin.systemd:
    name: lightdm.service
    enabled: true

- name: Install xfce themes
  become: true
  community.general.pacman:
    name:
      - xfce-theme-manager
      - elementary-icon-theme

- name: Install xfce themes
  kewlfft.aur.aur:
    name:
      - xfce-theme-greybird
      - shimmer-wallpapers
      - elementary-xfce-icons
      - paper-icon-theme-git
      - papirus-icon-theme-git
      - matcha-gtk-theme-git

- name: Install redshift
  become: true
  community.general.pacman:
    name:
      - redshift
      - python-gobject
      - python-xdg

- name: Install pdf viewer
  become: true
  community.general.pacman:
    name: evince

- name: Install archive tools
  become: true
  community.general.pacman:
    name: file-roller

- name: Install xterm
  become: true
  community.general.pacman:
    name: xterm
