---
- name: Install xorg
  become: true
  community.general.pacman:
    name:
      - xorg-apps
      - xorg-server

- name: Install desktop environment (xfce)
  become: true
  community.general.pacman:
    name:
      - accountsservice
      - gnome-keyring
      - gvfs
      - gvfs-afc
      - gvfs-mtp
      - lightdm
      - lightdm-gtk-greeter
      - network-manager-applet
      - seahorse
      - xdg-user-dirs
      - xfce4
      - xfce4-goodies

- name: Install lightdm configuration
  become: true
  ansible.builtin.template:
    dest: /etc/lightdm/lightdm.conf
    group: root
    mode: "0644"
    owner: root
    src: lightdm.conf.j2

- name: Enable lightdm
  become: true
  ansible.builtin.systemd:
    enabled: true
    name: lightdm.service

- name: Install xfce themes
  become: true
  community.general.pacman:
    name:
      - elementary-icon-theme
      - xfce-theme-manager

- name: Install xfce themes
  kewlfft.aur.aur:
    name:
      - elementary-xfce-icons
      - matcha-gtk-theme-git
      - paper-icon-theme-git
      - papirus-icon-theme-git
      - shimmer-wallpapers
      - xfce-theme-greybird

- name: Install redshift
  become: true
  community.general.pacman:
    name:
      - python-gobject
      - python-xdg
      - redshift

- name: Install pdf viewer
  become: true
  community.general.pacman:
    name: evince

- name: Install archive tools
  become: true
  community.general.pacman:
    name: file-roller

- name: Install xterm
  become: true
  community.general.pacman:
    name: xterm
