---
- name: Installing Xorg
  become: true
  community.general.pacman:
    name:
      - xorg-apps
      - xorg-server
    state: present

- name: Installing main XFCE packages
  become: true
  community.general.pacman:
    name:
      - accountsservice
      - gnome-keyring
      - gvfs
      - gvfs-afc
      - gvfs-mtp
      - lightdm
      - lightdm-gtk-greeter
      - network-manager-applet
      - seahorse
      - xdg-user-dirs
      - xfce4
      - xfce4-goodies
    state: present

- name: Copying LightDM configuration
  become: true
  ansible.builtin.template:
    dest: /etc/lightdm/lightdm.conf
    group: root
    mode: "0644"
    owner: root
    src: lightdm.conf.j2

- name: Enabling LightDM service
  become: true
  ansible.builtin.systemd:
    enabled: true
    name: lightdm.service

- name: Installing XFCE themes
  become: true
  community.general.pacman:
    name:
      - elementary-icon-theme
      - xfce-theme-manager
    state: present

- name: Installing XFCE themes from the AUR
  kewlfft.aur.aur:
    name:
      - elementary-xfce-icons
      - matcha-gtk-theme-git
      - paper-icon-theme-git
      - papirus-icon-theme-git
      - shimmer-wallpapers
      - xfce-theme-greybird
    state: present

- name: Installing redshift
  become: true
  community.general.pacman:
    name:
      - python-gobject
      - python-xdg
      - redshift
    state: present

- name: Installing a PDF viewer
  become: true
  community.general.pacman:
    name: evince
    state: present

- name: Installing archive tools
  become: true
  community.general.pacman:
    name: file-roller
    state: present

- name: Installing xterm
  become: true
  community.general.pacman:
    name: xterm
    state: present
