---
- name: Installing Lutris
  ansible.builtin.apt:
    name: lutris
    state: present

- name: Installing Lutris dependencies for running EA Origin
  ansible.builtin.apt:
    name:
      - libasound2-plugins:i386
      - libdbus-1-3:i386
      - libfreetype6:i386
      - libgnutls30:i386
      - libgpg-error0:i386
      - libldap-dev:i386 # libldap-2.4-2:i386
      - libsdl2-2.0-0:i386
      - libxml2:i386
    state: present
