---
name: Ansible Lint
on:
  push:
    paths:
      - 'arch/**'
      - 'debian/**'
      - 'macos/**'
      - 'rpi/**'
      - 'ubuntu/**'

jobs:
  main:
    name: ansible
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: pip3 install ansible ansible-lint
      - run: |
          mkdir ~/.ansible/plugins/modules
          curl -o ~/.ansible/plugins/modules/aur.py \
          https://raw.githubusercontent.com/kewlfft/ansible-aur/v0.10.0/plugins/modules/aur.py
      - run: |
          ansible-lint -c .ansible_lint \
            arch/arch.yml \
            debian/debian.yml \
            macos/personal.yml \
            macos/work.yml \
            rpi/rpi.yml \
            rpi/user.yml \
            ubuntu/ubuntu.yml
