---
name: Ansible Lint
on:
  push:
    paths:
      - 'arch/**'
      - 'debian/**'
      - 'workspace/**'

jobs:
  main:
    name: ansible
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ansible/ansible-lint-action@master
        with:
          targets: |
            arch/arch.yml
            debian/debian.yml
            workspace/workspace.yml
