---
name: Ansible Lint
on:
  push:
    paths:
      - 'arch/**'
      - 'debian/**'
      - 'macos/**'
      - 'rpi/**'
      - 'ubuntu/**'
      - 'workspace/**'

jobs:
  main:
    name: ansible
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: pip3 install ansible-lint
      - run: |
          ansible-lint -c .ansible_lint \
            arch/arch.yml \
            debian/debian.yml \
            macos/personal.yml \
            macos/work.yml \
            rpi/rpi.yml \
            rpi/user.yml \
            ubuntu/ubuntu.yml
