---
name: Lint
on: push

jobs:
  main:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ~/.ansible
          key: ansible-${{ hashFiles('requirements.yml') }}
      - run: pip3 install ansible ansible-lint
      - run: ansible-galaxy install -r requirements.yml
      - run: |
          mkdir -p ~/.ansible/plugins/modules
          curl -o ~/.ansible/plugins/modules/gpg_key.py \
            https://raw.githubusercontent.com/netson/ansible-gpg-key/master/gpg_key.py
      - uses: mfinelli/setup-shfmt@v1
      - run: |
          shellcheck --version
          shellcheck finellictl
          shellcheck arch/bootstrap arch/go arch/init arch/pacstrap \
            arch/server
          shellcheck debian/go
          shellcheck macos/go
          shellcheck rpi/fde rpi/go
          shellcheck ubuntu/go
          find . -name '*.bash' | xargs shellcheck
          find . -name '*.sh' | xargs shellcheck
      - run: |
          shfmt -s -i 2 -ci -sr -d finellictl
          shfmt -s -i 2 -ci -sr -d arch/bootstrap arch/go arch/init \
            arch/pacstrap arch/server
          shfmt -s -i 2 -ci -sr -d debian/go
          shfmt -s -i 2 -ci -sr -d macos/go
          shfmt -s -i 2 -ci -sr -d rpi/fde rpi/go
          shfmt -s -i 2 -ci -sr -d ubuntu/go
          find . -name '*.bash' | xargs shfmt -s -i 2 -ci -sr -d
          find . -name '*.sh' | xargs shfmt -s -i 2 -ci -sr -d
      - run: ansible-lint arch/arch.yml
      - run: ansible-lint debian/debian.yml
      - run: ansible-lint macos/personal.yml
      - run: ansible-lint macos/work.yml
      - run: ansible-lint rpi/rpi.yml
      - run: ansible-lint ubuntu/ubuntu.yml
