---
name: Lint
on: push # yamllint disable-line rule:truthy

jobs:
  main:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ~/.ansible
          key: ansible-${{ hashFiles('requirements.yml') }}
      - run: pip3 install ansible ansible-lint
      - run: ansible-galaxy install -r requirements.yml
      - run: |
          mkdir -p ~/.ansible/plugins/modules
          curl -o ~/.ansible/plugins/modules/gpg_key.py \
            https://raw.githubusercontent.com/netson/ansible-gpg-key/master/gpg_key.py
      - uses: mfinelli/setup-shfmt@v2
      - run: npm install -g prettier
      - name: Run shellcheck
        run: |
          shellcheck --version
          shellcheck finellictl
          shellcheck arch/bootstrap arch/go arch/init arch/pacstrap
          shellcheck debian/go
          shellcheck macos/go
          shellcheck rpi/go
          shellcheck ubuntu/go
          find . -name '*.bash' | xargs shellcheck
          find . -name '*.sh' | xargs shellcheck
      - name: Run shfmt
        run: |
          shfmt --version
          shfmt -s -i 2 -ci -sr -d finellictl
          shfmt -s -i 2 -ci -sr -d arch/bootstrap arch/go arch/init \
            arch/pacstrap
          shfmt -s -i 2 -ci -sr -d debian/go
          shfmt -s -i 2 -ci -sr -d macos/go
          shfmt -s -i 2 -ci -sr -d rpi/go
          shfmt -s -i 2 -ci -sr -d ubuntu/go
          find . -name '*.bash' | xargs shfmt -s -i 2 -ci -sr -d
          find . -name '*.sh' | xargs shfmt -s -i 2 -ci -sr -d
      - name: Run prettier
        run: |
          prettier --version
          find . -name '*.yaml' -o -name '*.yml' | xargs prettier -c
          find . -name '*.md' | xargs prettier -c
      - name: Run yamllint
        run: |
          yamllint --version
          find . -name '*.yaml' -o -name '*.yml' | xargs yamllint -f github
      - name: Run ansible-lint
        run: |
          ansible-lint --version
          ansible-lint arch/arch.yml
          ansible-lint debian/debian.yml
          ansible-lint macos/personal.yml
          ansible-lint macos/work.yml
          ansible-lint rpi/rpi.yml
          ansible-lint ubuntu/ubuntu.yml
