---
name: Shell
on:
  push:
    paths:
      - .github/workflows/shell.yml
      - arch/bootstrap
      - arch/go
      - arch/init
      - arch/pacstrap
      - debian/go
      - '**.bash'

jobs:
  shellcheck:
    name: shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run shellcheck
        run: |
          shellcheck --version
          shellcheck arch/bootstrap
          shellcheck arch/go
          shellcheck arch/init
          shellcheck arch/pacstrap
          shellcheck debian/go
          find . -name '*.bash' | xargs shellcheck

  shfmt:
    name: shfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download shfmt
        run: |
          wget -O shfmt https://github.com/mvdan/sh/releases/download/v3.2.0/shfmt_v3.2.0_linux_amd64
          chmod +x shfmt
      - name: Run shfmt
        run: |
          ./shfmt --version
          ./shfmt -s -i 2 -ci -sr -d arch/bootstrap
          ./shfmt -s -i 2 -ci -sr -d arch/go
          ./shfmt -s -i 2 -ci -sr -d arch/init
          ./shfmt -s -i 2 -ci -sr -d arch/pacstrap
          ./shfmt -s -i 2 -ci -sr -d debian/go
          find . -name '*.bash' | xargs ./shfmt -s -i 2 -ci -sr -d
