---
- name: Add mega signing key
  ansible.builtin.apt_key:
    keyring: /usr/share/keyrings/meganz-archive-keyring.gpg
    # url: https://mega.nz/keys/MEGA_signing.key
    url: https://mega.nz/linux/repo/xUbuntu_{{ ansible_distribution_version }}/Release.key

- name: Add mega apt repository
  ansible.builtin.apt_repository:
    filename: megasync
    repo: >
      deb [signed-by=/usr/share/keyrings/meganz-archive-keyring.gpg]
      https://mega.nz/linux/repo/xUbuntu_{{ ansible_distribution_version }}/ ./
    update_cache: true

- name: Install megasync
  ansible.builtin.apt:
    name: megasync
