---
- name: Creating Dropbox install directory
  ansible.builtin.file:
    group: root
    mode: "0755"
    owner: root
    path: /opt/dropbox-{{ dropbox_version }}
    state: directory

- name: Downloading Dropbox client
  ansible.builtin.unarchive:
    dest: /opt/dropbox-{{ dropbox_version }}
    group: root
    owner: root
    remote_src: true
    src: "https://clientupdates.dropboxstatic.com/dbx-releng/client/\
      dropbox-lnx.x86_64-{{ dropbox_version }}.tar.gz"

- name: Linking Dropbox binary
  ansible.builtin.file:
    dest: /usr/bin/dropbox
    src: "/opt/dropbox-{{ dropbox_version }}/.dropbox-dist/\
      dropbox-lnx.x86_64-{{ dropbox_version }}/dropbox"
    state: link

- name: Installing Dropbox icon
  ansible.builtin.get_url:
    dest: /usr/share/pixmaps/dropbox.svg
    group: root
    mode: "0644"
    owner: root
    url: "https://aur.archlinux.org/cgit/aur.git/plain/\
      DropboxGlyph_Blue.svg?h=dropbox"

- name: Installing Dropbox desktop entry
  ansible.builtin.copy:
    dest: /usr/share/applications/dropbox.desktop
    group: root
    mode: "0644"
    owner: root
    src: dropbox.desktop
