---
base_use_backports_firmware:
  - bowser

base_use_backports_kernel:
  - bowser

base_supermario_repo_host: "https://download.opensuse.org/repositories/home:/\
  mfinelli:/supermario/"

base_architectures:
  armv6l: armhf
  armv7l: armhf
  aarch64: arm64
  x86_64: amd64
  i386: i386

base_zfs_hosts:
  - kleio

base_zfs_pools:
  kleio:
    - tank

base_attached_storage:
  bowser:
    - group: mario
      keyfile: /root/datadiskkey
      label: DATADISK
      fstype: btrfs
      mountpoint: /mnt/data
      name: datadisk
      owner: mario
  kleio:
    - label: GITDATA
      name: gitdata
      fstype: ext4
      mountpoint: /mnt/gitdata
      keyfile: /root/gitkey
    - label: URLWATCHDATA
      name: urlwatchdata
      fstype: ext4
      mountpoint: /var/lib/urlwatch
      keyfile: /root/urlwatchkey
      owner: urlwatch
      group: urlwatch
    - label: SHDATA
      name: shdata
      fstype: ext4
      mountpoint: /mnt/shdata
      keyfile: /root/shkey
    - label: WARCDATA
      name: warcdata
      fstype: ext4
      mountpoint: /mnt/warcdata
      keyfile: /root/warckey

base_attached_storage_options:
  btrfs: rw,relatime,compress=zstd:3,space_cache=v2,subvol=/
  ext4: defaults,noatime
