---
base_use_backports_kernel: true # TODO: can probably switch off with forky

base_supermario_repo_host: "https://download.opensuse.org/repositories/home:/\
  mfinelli:/supermario/"

base_architectures:
  armv6l: armhf
  armv7l: armhf
  aarch64: arm64
  x86_64: amd64
  i386: i386
